### PR TITLE
Tweak the appearance of several textures

### PR DESCRIPTION
**Pull request by MirceaKitsune**
One thing that always bothered me in Minetest is that the environment often looks dead and depressing, and the world generally feels deprived of essence and artistic taste. I decided to try fixing this a bit, by tweaking several default textures to give the environment a better feel.

I primarily adjusted the brightness and saturation of textures I considered ugly, in an attempt to make some a bit more warm and colorful whereas a few seemed oversaturated or too sharp. The only exception is the dirt texture, which I ported back from the previous texture package but tweaked it to be a bit more like the current one. It's the only texture who's replacement I disliked at the time... mostly because I like the patterns on it, whereas the current dirt texture looks very muddy and boring.

Below are screenshots highlighting the main differences. Please let me know what you think, and if you believe I should tweak anything more. There will probably be different tastes and opinions and a vote might be required, but I think this (or something like it) should really be considered over the existing default atmosphere.

Ground, before: http://i.imgur.com/RvrhCx5.jpg
Ground, after: http://i.imgur.com/MHeDA3O.jpg
Water, before: http://i.imgur.com/kyzs74X.jpg
Water, after: http://i.imgur.com/nHi54k1.jpg

### CODE REVIEW

**Comment by MirceaKitsune** [comment]
Ugh... re-uploading the screenshots on Tinypic, Imgur seriously has no regard for image quality:

Ground, before: http://i59.tinypic.com/2j1ogtu.png
Ground, after: http://i58.tinypic.com/vgluh5.png
Water, before: http://i60.tinypic.com/rbgkgo.png
Water, after: http://i60.tinypic.com/30muvqs.png

**Comment by est31** [comment]
Water and grass color should be dependent on the biome.

**Comment by est31** [comment]
[This](http://visibleearth.nasa.gov/view.php?id=57730) might serve as a reference.

**Comment by MirceaKitsune** [comment]
@est31 Colorizing grass based on area is currently not possible. It would require heavy code changes, and so far no one's taken this task on. If anyone will, I'll gladly make a grayscale version of the texture and enable biome based coloring! This is however for later on.

**Comment by C1ffisme** [comment]
I have really bad eyes, so I'm no person to say this, but I can't see any difference at ALL.

**Comment by MirceaKitsune** [comment]
@C1ffisme Perhaps see the images at maximum resolution. There are subtle differences... such as the grass being a bit brighter and more saturated, and the old dirt texture being re-included. It's mostly to make the general atmosphere somewhat nicer, and to improve a few textures which always seemed ugly for various reasons.

**Comment by C1ffisme** [comment]
Maybe if I saw the images right next to each other. I have to combine my worst attributes, my eyesight and memory.

**Comment by est31** [comment]
On firefox browser there is the `ctrl+pgup`/`ctrl+pgdown` functionality to switch tabs

**Comment by C1ffisme** [comment]
The grass DOES look brighter, although I'm now depressed with tinypic for showing steroid drug advertisements.

**Comment by kilbith** [comment]
@MirceaKitsune : please move your screenshots directly in your posts (not linked elsewhere), and ideally  show the "before/after" for each texture change in the same image.

**Comment by BlockMen** [comment]
No, it IMO no improvement. Also you reverted the dirt texture. Won't go in as is.

**Comment by MirceaKitsune** [comment]
@BlockMen I think the patterns on the old dirt texture were a lot better and added more detail, whereas the existing dirt is more grainy but looks muddy and overall too simple. To get the best out of both, I now combined the two and pushed my changes. I think the resulting texture looks a lot better! It has both the rocky patterns in the first, as well as the grainy feel in the current.

Screenshot of the new combined dirt texture: http://i62.tinypic.com/14iq6gx.jpg

In regard to the others, the changes are usually minor and not as noticeable directly. Like I said, the main purpose was to tweak the color tones of a few textures which seemed too gray, in an attempt to make the default texture package feel more lively and welcoming.

**Comment by paramat** [comment]
I think the current water is fine and shouldn't be changed, however c55, hmmmm and myself consider the current grass texture too dark and grim, try minimal game to see how uplifting and sunny the original texture was. 
Dirt is okay but perhaps too light brown, i personally would like a richer darker-brown soil colour.

**Comment by Wayward1** [comment]
I originally preferred the new dirt and grass texture over the old one, but I think the combined textures are even better

**Comment by MirceaKitsune** [comment]
Anything new on this please? Can it be accepted, even in part (some textures)? Do people like the tweaks overall, and believe the livelier feel I tried achieving is an improvement?

**Comment by paramat** [comment]
I feel that only your new grass (top of dirt_with_grass) is acceptable, seeing as hmmmm, c55 and myself consider it too dark and dull, nothing else needs changing. Long plantlike grasses have already recently been brightened.
Your screenshots should ideally not have bumpmap/occlusion shaders applied as this changes the appearence and darkness.

**Comment by paramat** [comment]
These textures have now been updated in MTGame:
Grass
Grass side
All long grasses
Ice
Jungletree top

I don't like the water, too light.

For these others can you provide before/after screenshots and/or enlargements? It's a lot of work for us to compare:
Glass
Gravel
Jungleleaves
Jungletree
Tree
Tree top
Leaves
Pine tree
Pine tree top
Sign
Snow
Snow side

As far as i can see you have mostly increase saturation and brightness?
Note that pine tree is meant to be greyish so more saturation is not good.

**Comment by MirceaKitsune** [comment]
This can probably be closed. If anything, I'd have to re-make them based on the existing textures.

**Pull request closed without merging**
