### PR TITLE
Biomes: Improve biome system and v6 mushroom spawning WIP

### PR DESCRIPTION
**Pull request by paramat**
More complex distribution of dry grasses
Spawn mgv6 mushrooms by trees
Match mgv5/v7 mushrooms to tree density
Remove water below glacier rivers
Gravel as glacier seabed
Do not force-place acacia root
Rename spore nodes
Use single ABM for mushroom growing
Tune acacia tree density

### CODE REVIEW

**Comment by paramat** [comment]
@kilbith i agree mushrooms should be in shady areas, although i tried to avoid 'spawn by' it's the only way in mgv6. In mgv5/v7 the noise is matched to tree density.

**Comment by kilbith** [comment]
You could also use `minetest.find_node_near(pos, {1-3}` and check for a list of trees to spawn around.

**Comment by paramat** [comment]
Update: do not force-place acacia root node (to keep other devs happy).

**Comment by kilbith** [comment]
While you're touching that code, can you please replace : 

``` Lua
description = string.sub(string.upper(name), 0, 1) ..
            string.sub(name, 2) .. " Mushroom",
```

By : 

``` Lua
description = string.gsub(name, "%l", string.upper, 1) .. " Mushroom",
```

**Comment by paramat** [comment]
Okay.
Also i think the spores should be named flowers:mushroom_spores_brown/red instead of flowers:spores_brown/red.
I hope the devs agree that's clearer, sorry for the sloppy naming.

**Comment by paramat** [comment]
Updated with changed spore names.

@kilbith your changes to description caused an error.

**Comment by kilbith** [comment]
Which error ? I don't see how. Just copy-paste the above correctly.

**Comment by paramat** [comment]
I'll try again and copy the error here if it happens again.

This commit has become overloaded now, i will split it into 2 new commits.

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.ru/minetest-dev/2015-08-07#i_4354808
Will close and spilt into 2 new commits.

**Pull request closed without merging**
