### PR TITLE
Flowers: Add waterlily and add to mapgen

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150916_080835

New PR for #657 
Texture is by Gambit, from the excellent Pixelbox2 texture pack.

In mgv6 waterlilies only appear in dirt ocean.
In mgv5 and mgv7 there is no dirt ocean, the waterlily schematics force-place a dirt node in the ocean bed.

Waterlilies can be placed on water, they randomly rotate when this is done. Due to how the 'after place node' function works a waterlily must be placed on water which has at least 1 water source as a neighbour.

### CODE REVIEW

**Comment by kilbith** [comment]
FYI, `minetest.add_node` has been deprecated to `minetest.set_node`. Otherwise :+1:

**Comment by PilzAdam** [comment]
Seems good. An additional feature for the future might be regrowing if on water and near dirt with grass.

**Comment by paramat** [comment]
Changed 'add node' to 'set node', i found out that 'add node' is deprecated.
Changed distribution to be similar to papyrus, waterlily areas are 1/3rd of world area instead of one half, they were too common. Within these areas they occasionally get fairly dense, sometimes it's possible to parkour over a shallow lake on the lilypads, fun.

**Comment by paramat** [comment]
Fixed bug, biome list needed 'rainforest swamp' not 'rainforest ocean'.

**Comment by paramat** [comment]
4bb9652c0f6c1736ca325ed94aaff10be9a11b47

**Comment by 0-afflatus** [comment]
:+1:
When river water is included could water lilies be limited to freshwater?

**Pull request closed without merging**
