### PR TITLE
Default/nodes: Make water, lava and ice is_ground_content = false

### PR DESCRIPTION
**Pull request by paramat**
screenshot_2015-04-04t23 41 44

Mgv6 snow biomes have icesheet which is currently eaten by cavegen. More generally, ice is usually used for icebergs and icesheet, at or below water level, so should not have caves.

### CODE REVIEW

**Comment by PilzAdam** [comment]
This screenshot looks actually pretty interesting. A flat icesheet would be quite boring here.

**Comment by MT-Modder** [comment]
I agree with @PilzAdam. It looks like a bug but it makes it look weathered.

**Comment by Megaf** [comment]
I agree with @paramat that should not happen.
I agree with @PilzAdam and @MT-Modder It is very interesting and make the game more fun.

What do we do now?

**Comment by RHRhino** [comment]
> I agree with @paramat that should not happen.
I agree with @PilzAdam and @MT-Modder It is very interesting and make the game more fun.
What do we do now?

Flip a coin :wink:

**Comment by paramat** [comment]
screenshot_2015-04-04t23 44 41


It does look quite interesting in that first screenshot, but as you can see here near the icesheet edge, the water level is much lower in the ice caves. When a cave crosses the icesheet edge you then get a waterfall running into the cave. I actually find an unbroken icesheet looks and feels much better, it will still have occasional glitches where dungeons form within it.
So i still very much want to merge this.

**Comment by C1ffisme** [comment]
Maybe caves should be prevented in ice sheets thicker than a certain amount. That way thin ice has caves and cracks, and thick ice looks stronger.

**Comment by paramat** [comment]
Detecting ice thickness would be too complex and processing heavy.

**Comment by paramat** [comment]
Cracks in ice is an okay idea, i have these in one of my mapgens, but water level should be normal in the cracks, and they should be a continuous network of thin cracks instead of isolated blobs.

**Comment by C1ffisme** [comment]
Alright then.

**Comment by kilbith** [comment]
Sorry, I don't really like... 5m of ice thickness with craters is not realistic and don't ease the access to the water.

**Comment by paramat** [comment]
It can be made thinner no problem, 4m is quite thick, i was considering 2m or 4m. But that's more of a snowbiomes issue.

**Comment by kilbith** [comment]
2m would be a good balance, yes.

**Comment by paramat** [comment]
Okay will do.

**Comment by paramat** [comment]
Also made water and lava not ground content, this will simplify and speed up cavegen checks for which nodes to remove.

**Comment by paramat** [comment]
Merged fe7a982343c2836e61b44743bf28115c7df7abb2

**Comment by MT-Modder** [comment]
After those other screenshots I don't like the look of it. Thank you paramat.

**Pull request closed without merging**
