### PR TITLE
Default: New grass, grass side, snow side textures WIP

### PR DESCRIPTION
**Pull request by paramat**
This is PilzAdam's Nodetopia texture with colour saturation increased by 24 in Gimp.
I have tried to match the brightness and saturation to our current texture and our previous 0.4.10 texture.
The side texture extends roughly 3/4 of the way down the side to make the sides of hills look grassy.
The pattern of the grass fringe is copied from our current texture, translucent shading is added for a slight shadow effect under the fringe.

The advantage of this texture is that it is not too different from what we have now, in being rather featureless pixel noise, but it has less contrast and less colour variation so is visually smoother and a purer green, i find the yellowy colour variation in our current texture sickly.

The grassy sides give the terrain a lusher greener look, and i feel this is a good opportunity for Minetest to become more individual by moving away from the exposed-side-dirt look of Minecraft.
Although many players are used to the look from Minecraft, i have always found it strange and ugly for a grassy hill to look like mostly dirt when seen from the side.

I still need to create the 'dirt with snow' side texture.

My submitted textures for you to try:

default_grass_nt_sp24 default_grass_nt_side_lower_sp24

Comparison. New texture above, current texture below:

default_grass_nt_sp24_128
default_grass_current_128

### CODE REVIEW

**Comment by RHRhino** [comment]
@paramat is it really necessary to change the grass texture before every release?

**Comment by paramat** [comment]
Nope :) As explained in the issue, my editing of our previous texture for 0.4.13 stable was a mistake, i was unhappy with it very soon after. If something needs doing then the time since the previous change should not be used as an argument against it, as with code. This texture is similar to what we have now so is not a big change, apart from the longer sides.

**Comment by kilbith** [comment]
I find the tall grass a bit inconsistent with your new texture. Your grass looks more "natural" and bland while the tall grass is "cartoon-ish" and more suited with the regular grass of PixelBOX (which have a better pattern & coloring btw).

screenshot_20151226_192731

**Comment by paramat** [comment]
kilbith, okay, however my submission is a very similar style to our current texture. I like the way long grass stands out, perhaps because my submission had less contrast.

**Comment by kilbith** [comment]
One thing also : some normal maps (if not all) must be removed for not causing relief mismatches with the new textures.

**Comment by paramat** [comment]
Yeah, im not bothering with those. The tools for creating normalmaps in Gimp don't give good results (i tried it), RBA recommends compiling another program to create the maps, the process is not easy, i think this is too much to ask of texture creators so i consider it RBA's job to update the normalmaps.

I also dislike the half-finished and sloppy normalmap feature and they clutter the textures file and make it ugly, personally i'd like to see normalmaps removed although i know they're popular so have little hope.

**Comment by MoNTE48** [comment]
I can see horizontal lines on a grass field. It is very disgusting to me.

**Comment by paramat** [comment]
screenshot_20151226_191039

This is with 'make seamless' in Gimp, if people prefer this.

**Comment by Calinou** [comment]
It looks like it lacks contrast (in the latest screenshot).

**Comment by paramat** [comment]
Yes the 'make seamless' process has reduced the amount of contrasting detail slightly, i think now i prefer the original in the first post.
A tiled texture will always create a subtle pattern even after 'make seamless' processing.

**Comment by MoNTE48** [comment]
@paramat Do you want to use is not the ideal texture to in Minetest 0.4.14-dev again to change it? =)
I also believe that on the side of the texture of the ground with grass slick lot of grass. Grass should be reduced by 3px.

**Comment by sofar** [comment]
I've been attempting to do roughly the same, and I find any automated method for making things look seamless futile, as the human mind continues to find patterns where there are no patterns. With only 16x16, it's truly mathematically impossible to make something that's mostly green, pixelized, and not show patterns.

However, I've had good results by manually pixelizing and de-patterning bitmaps, so I just did the same for the grass pattern. The result is fairly decent:

![default_grass]
(http://i.imgur.com/2EPBkRq.png)

![large sample]
(http://i.imgur.com/cxTF2Vq.png)

**Comment by kilbith** [comment]
+1 for @sofar tile. And I agree that the grass side should be a little higher for compromise.

**Comment by paramat** [comment]
@sofar that's an improvement over the 0.4.13 texture, less contrast and it seems to have less of the unpleasant colour variation too.

Dirt will still be showing on steeper slopes and on the edge of cliffs. My attitude to this is that the most gentle possible slope in Minetest, which are 45 degrees, should be completely grassy, for gentle hills. Any steeper can then start to break up and show dirt. This is why i would like the sides to hang as low as possible as in the PR.

**Comment by sofar** [comment]
I did a quick pass over my previous texture, and
- further reduces contrast (both by reducing overall contrast, and lightening the most dark spots)
- removed the remaining aliasing effects I experienced.

![x16]
(http://i.imgur.com/IATn9pB.png)

![x256]
(http://i.imgur.com/O6NRCG9.png)

The result is quite decent. There's a hint of brown, enough local contrast but overall quite pleasantly green. The overall contrast is low enough that @paramat should be fine with it :^)

@paramat can from this version redo the side texture as he sees fit, if he wants to.

**Comment by sofar** [comment]
Preview (ignore the high sides)

![preview]
(http://i.imgur.com/d2rer1p.png)

**Comment by paramat** [comment]
Looks good, very smooth and less tiling issues than the nodetopia texture, i'll make a side tecture to test this out.

**Comment by C1ffisme** [comment]
@sofar I would make it just a tad darker, but that is just my opinion.

Otherwise, :+1: . It looks smooth, and not too flashy, nor does it show any repeating patterns.

**Comment by paramat** [comment]
I feel we should continue to consider various alternatives and post screenshots, that was what the issue was for but it became quiet, this PR has woken people up a bit =)

**Comment by sofar** [comment]
if people want me to "de-alias" other proposed textures, please ask. I'd be happy to do so for other people's textures.

**Comment by paramat** [comment]
Too early for a PR, we should consider the options.

**Pull request closed without merging**
