### PR TITLE
Allow for shift+clicking inventory into trash

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Fixer-007** [comment]
Nice, I was thinking about the same but never opened the issue. :+1:

**Comment by C1ffisme** [comment]
Pretty good to have this, makes building be quicker.

**Comment by kilbith** [comment]
Approved (as the author of the inventory).

**Comment by everamzah** [comment]
Do you want enter key inputting search queries, too?
https://www.youtube.com/watch?v=gX-fNU_TNco
https://github.com/everamzah/creative

**Comment by DonBatman** [comment]
Please add enter for search queries

**Comment by kilbith** [comment]
> Do you want enter key inputting search queries, too?

Your code is utterly hacky, so no.

It's not clean to latently call a formspec inside `fields.quit`. Also, it redirects to a regular player's formspec, not a detached inventory. Big :-1:

**Comment by everamzah** [comment]
My thoughts exactly.  This PR simply adds the listring[], which is super handy.

**Comment by kilbith** [comment]
> Except for the redirection part which I don't understand, but that's another topic.

`minetest.show_formspec` is server-side and subject to lag. A detached inventory is not tied to anything (player or node) and thus not subject to lag. The logic you made is leaving the detached inventory and redirect to a player's formspec, which is dirty. The engine should be modified instead of hacking around. But yes, another topic...

**Comment by kilbith** [comment]
Integrated in https://github.com/minetest/minetest_game/pull/945, as it's very minor.

Feel free to close your PR.

**Pull request closed without merging**
