### PR TITLE
Add a crosshair with shadow for visibility

### PR DESCRIPTION
**Pull request by Ferk**
This is a follow up on #401 
I also added the clarification on the license from Calinou, just as he did on his PR.

This crosshair is thin (2 pixels wide), not very intrusive and it's visible both in dark and light nodes. I've been using it for about a week and while it's very similar to the default one it's much nicer on white backgrounds.

crosshair

screenshot 15
screenshot 16

### CODE REVIEW

**Comment by paramat** [comment]
+1 from me.

**Comment by paramat** [comment]
Sorry not keen on this now, it's practical but seems too 3D, i like the flatness of the simple hardcoded crosshair, i don't feel the visibility is enough of a problem to need a new one.

**Comment by kilbith** [comment]
In fact we should stick with the current crosshair : the clear nodes are already clearly outlined in black with their selection boxes, making the crosshair's visibility unnecessary.

**Comment by paramat** [comment]
Yes.
The hardcoded crosshair is probably more lightweight too, not having to use a texture.
Sorry Ferk to change my mind after encouraging you.

**Comment by kaeza** [comment]
I think a crosshair with alternating white/black pattern (lines or dots) would be better. Or a black border around the whole cross.

**Comment by paramat** [comment]
> a crosshair with alternating white/black pattern (lines or dots) would be better

Yes that might be okay because it would be flat and no more intrusive than current. Whatever we do it should be hardcoded for speed, the use of a texture is for modification by texture packs.

**Comment by Ferk** [comment]
>  a crosshair with alternating white/black pattern (lines or dots) would be better.

I tried that before I draw this one, and no matter what pattern I tried it looked very ugly.

This shadow pattern was the smoothest and most plain of the lot. If what's not acceptable about it is the looks and not just the fact that it adds a texture then I guess writing a hardcoded routine to draw it in the engine would be wasted time.

> Sorry Ferk to change my mind after encouraging you.

That's ok, it was a 10 minutes thing and I'm happily using it in a texture pack anyway. No hard feelings :)

**Comment by Ferk** [comment]
Imho, this should be closed if it's not gonna be merged.
I doubt there's an alternative that could be accepted (regardless if texture or coded), so I guess the crosshair should stay like it is.

**Pull request closed without merging**
