### PR TITLE
Change furnace fire icons

### PR DESCRIPTION
**Pull request by Kalabasa**
By furnace fire icon, I mean the fire image between the fuel and the cookable item in the furnace screen.

The current one looks too rectangulary; the sides are cut as if it's a side-tileable texture. (And indeed it tiles nicely)

I remade the fire more rounded so it does not look as rectangulary. I also made the fire not too violent. I may have made it too colorful. I got colors from fire reference pictures.

| Before | After |
| --- | --- |
| fire before | fire after |

I also made the background color the same as the arrow's background color. I noticed the arrow bg has a drop shadow, but I can't recreate it in the fire bg because it's low res.

| Before | After |
| --- | --- |
| bg before | bg after |

Full view:
furnace screen before
furnace screen after

### CODE REVIEW

**Comment by Heybye44** [comment]
👍



—

**Comment by CraigyDavi** [comment]
:+1:

**Comment by MT-Modder** [comment]
:+1:

**Comment by ShadowNinja** [comment]
:+1:

**Comment by RHRhino** [comment]
nice :+1:

**Comment by kilbith** [comment]
:yellow_heart:

**Comment by Novatux** [comment]
Looks good

**Comment by sfan5** [comment]
554d15fadb507335a035933f0db55b3e84277fbb

**Pull request closed without merging**
