### PR TITLE
Default: New ice texture by Gambit

### PR DESCRIPTION
**Pull request by paramat**
newice

### CODE REVIEW

**Comment by kilbith** [comment]
You can close https://github.com/minetest/minetest_game/pull/555 now, since it's a duplicate.

**Comment by est31** [comment]
:+1: (to the pr, not @kilbith's comment. I favour different "dupe pr" closing strategies. PRs are suggestions how to do something).

**Comment by kilbith** [comment]
@est31 RBA admitted that this ice texture is better (and besides : got a positive unanimity), hence there's no need to a dupe.

**Comment by est31** [comment]
Thats an argument, close is OK, in this case.

**Comment by asl97** [comment]
:-1: to be honest, i don't really like it that much, you can't see it in the screenshot by @paramat but you might be able to see it in this screenshot

screenshot_20150710_083904

the one by @RealBadAngel doesn't have that much of a grid look.

**Comment by paramat** [comment]
Yes there's a slight grid look from above but i still prefer Gambit's original texture, it looks better from a ground perspective, has more character and is more shiny. I prefer to stay with an artist's design and not alter it if possible.

**Comment by asl97** [comment]
@paramat it just need one or two pixel edited, i admit i might have over did it the first time.
i lengthen small line by a single pixel at where i was pointing at in the first picture and move another pixel

i think there is still a grid in the background but maybe i am just seeing things.

ps: i got lazy and just took a screenshot of it in my editor instead of in game.
ice_mass
ice

**Comment by kilbith** [comment]
@asl97's texture is certainly an improvement since it breaks the grid and makes some stripes shorter.

**Comment by paramat** [comment]
asl97 i like that much more and would be happy with either, the mtgame team can decide between the two.

**Comment by VanessaE** [comment]
@asl97 's "after" image in https://github.com/minetest/minetest_game/pull/562#issuecomment-120205071 looks the best to me.

**Comment by paramat** [comment]
Changed my mind, i like asl97's most recent texture, i would be happy with either that or Gambit's original.

**Comment by RealBadAngel** [comment]
Point of my attempt was to get rid of the grid, so i vote for the altered one

**Comment by sfan5** [comment]
I agree with @VanessaE, @asl97's modified texture looks best
(this one: )

**Comment by paramat** [comment]
Can any MTGame team member give this the second +1?

**Comment by kilbith** [comment]
This is so cosmetical stuff that you don't need to. Go ahead.

**Comment by Novatux** [comment]
Both textures look good: so you can merge the one sfan5 suggested.

**Comment by paramat** [comment]
Okay thanks will push the edited one later.

**Comment by paramat** [comment]
fdae2832bb736444b3052acffd30fafd6f823e99

**Pull request closed without merging**
