### PR TITLE
Convert stairs in meshnode

### PR DESCRIPTION
**Pull request by kilbith2**
According to @RealBadAngel, using a meshnode on stairs permits to delete 4 duplicate vertices (see sketch below) and thus give a speedup since those nodes are massively used.

The appareance is unchanged compared to the nodebox model.

stair

qd

### CODE REVIEW

**Comment by sfan5** [comment]
:+1:

**Comment by C1ffisme** [comment]
It's true that this may fix some rendering problems and speed it up by a little, but we also have to consider that this is one of the few blocks that is a nodebox. So we have to decide if we want to keep an example of a nodebox for modders, or make them 0.1 seconds faster.

I dunno, how much faster does this make rendering?

**Comment by paramat** [comment]
+1 yes please.

**Comment by MT-Modder** [comment]
:+1:

**Comment by RealBadAngel** [comment]
@C1ffisme nodeboxes are relict of the days past, in the engine theyre already converted to meshes.
Meshnodes are WAY faster.
What are we waiting for with this? Christmas?

**Comment by ExcaliburZero** [comment]
:+1:

**Comment by RealBadAngel** [comment]
mtgame team. kindly asking you to stop fooling around and merge such obvious things...
wake up for christ sake :)

**Comment by kilbith** [comment]
This is a quality-reason why @paramat should be game maintainer for his perpetual careness and attention. [/offtopic]

**Comment by RealBadAngel** [comment]
this is not hunderds line change, so team should deliberate for weeks. its trivial and effect of the change is clear.

**Comment by paramat** [comment]
I think one +1 from sfan5 is enough, combined with RBA's approval, as this is fairly trivial and not a new feature.

**Comment by kilbith** [comment]
Or can we consider core-dev's +1 == 0.5 points on minetest_game's PRs ?

**Comment by paramat** [comment]
Merge approved by sfan5 http://irc.minetest.ru/minetest-dev/2015-07-08#i_4314587

f3f8b22698303c1ee592ea5e9d5ba5ce1427ce57

**Pull request closed without merging**
