### PR TITLE
Sam III

### PR DESCRIPTION
**Pull request by kilbith**
This is **Sam III** from stu (WTFPL) : https://forum.minetest.net/viewtopic.php?f=5&t=5768
- Articulated knees and elbows.
- Hat layer support.
- 2x lighter than Sam II (138 KB against 316 KB), thanks to the efficient B3D conversion.

rendercr

### CODE REVIEW

**Comment by ShadowNinja** [comment]
I like the new model, but not the new texture.

**Comment by kilbith** [comment]
Suggestions for the texture ?

**Comment by ShadowNinja** [comment]
I think the current one is good.

**Comment by Novatux** [comment]
Looks good

**Comment by sfan5** [comment]
I also think the current texture is better.

Can you show an im-game comparison?

**Comment by kilbith** [comment]
(I remit the current skin for Sam III)

@sfan5 : sure.

**Sam II**
screenshot_582972826

**Sam III**
screenshot_582863463

P.S.: it concerns an animated model. The screenshots doesn't offer a good point of view for judging it.

**Comment by PilzAdam** [comment]
Does this still support the hat layer?

**Comment by kilbith** [comment]
@PilzAdam : yes, it support the hat layer : https://lut.im/5ACrXy4f/TqXJebLR (top-right part of the skin image colored in green).

**Comment by paramat** [comment]
Absolutely no way, this would be a huge mistake. Elbows and knees make it look creepy and no longer cute, abstract straight limbs in their silly cartoon-like motion are what make a MC/MT character adorable (see 'uncanny valley' http://en.wikipedia.org/wiki/Uncanny_valley). Again this is making the mistake of moving towards realism, voxel games are inherently simplistic and absract and look worse with excessive realism.

**Comment by kilbith** [comment]
@paramat : VoXus is all focused on cartoon-ish style. minetest_game tends to focus on visual realism (you seems have a chronic discontent against that theme). Otherwise I'm agree with you about the elbows permanently bent while walking, it should swing rather.

**Comment by Jordach** [comment]
kilbith; I vote no.

Some skins that players use are broken due to how the UV map is handled by
the model.

Because the wrist's top face uses the same as the top of the shoulder,
meaning some skins look completely incorrect.

**Comment by kilbith** [comment]
@Jordach : OK, that gives me a good reason to close this PR then.

**Comment by paramat** [comment]
Yep certainly our textures are fairly realistic, i use them and like them. But because this is a voxel game the shapes and drawtypes used are extremely abstract and simple, so it's quite right i continue to warn against more realism / higher resoluion / more complex shapes.

**Pull request closed without merging**
