### PR TITLE
Default/book: textarea -> table

### PR DESCRIPTION
**Pull request by ghost**
screenshot_20151004_221819-min
#690

### CODE REVIEW

**Comment by tenplus1** [comment]
+1

**Comment by kilbith** [comment]
A bit of attention to this PR please.

**Comment by paramat** [comment]
+1 for the feature but i can't judge implementation another dev needs to.

**Comment by Amaz1** [comment]
The only problem I see with this (which is an excellent fix!) is that lines are no longer wrapped, so if you want to be able to read things, you need to press enter after every line, not really a big deal though.

**Comment by paramat** [comment]
Approval http://irc.minetest.ru/minetest-dev/2015-10-18#i_4427013

**Comment by paramat** [comment]
3fb6ee5bdf7a8940d7e25c96f41436a49fea32fc

**Comment by Ferk** [comment]
> lines are no longer wrapped

Wouldn't this break previous books?

Maybe we could try and do line wrapping manually?

Or actually make textarea scrollable if too big in the engine... which seems like the right thing to do. After all, I can't imagine a more appropiate use of textarea than blocks of text like the ones in books.

**Pull request closed without merging**
