### PR TITLE
Move documentation for game to markdown format.

### PR DESCRIPTION
**Pull request by red-001**
This allows GitHub to display the documentation with proper styling  making it easier to read and use as a reference. 
See: #798. 
[Link to file in markdown](https://github.com/red-001/minetest_game/blob/better_game_api-doc/game_api.md)

### CODE REVIEW

**Comment by sofar** [comment]
This blows away all git history, and many lines are similar before and after

can you instead of copying, do

```
git mv game_api.txt game_api.md
```

And then incrementally fix the markup format where needed?

**Comment by red-001** [comment]
@sofar sorry about that I did do that but squashing removed it from history. Will fix soon.

**Comment by red-001** [comment]
Does that mean two commits?

**Comment by sofar** [comment]
Those 2 commits look fine to me - at least there's some coherence in what was changed, and unchanged lines are present (good).

**Comment by paramat** [comment]
rubenwardy wrote > lua_api.txt is in markdown, but hasn't been renamed for some reason

There may be a good reason for this, the document should always be quickly and simply openable as a text document, as far as i can remember this was a request from celeron55. I don't like markdown format and also don't like using a special program to open a document. Our documents should always be primarily intended to be simple text documents.

For now it should remain as .txt. until we find out why lua_api.txt remains that way.

**Comment by red-001** [comment]
It's no harder to open a .md document as a text then to open a .lua and minetest modding requires a *lot* of the second.

**Comment by paramat** [comment]
Sorry, you're probably right on that. Would opening a .md file in github display as text or MD? i want to see the text version.

**Comment by sofar** [comment]
github automatically displays all md files as markdown, not plain text.

**Comment by rubenwardy** [comment]
But you can click "raw" to view the raw file.

**Comment by paramat** [comment]
Okay, i do remember c55 insisting on lua_api.txt remaining a txt file, and i agree, when i go to the file in github it will be irritating to need another step to see the actual text file, devs are used to it as text and want to see it like that.
So my opinion is update this PR so we can merge the editing, and later we can discuss the file extension.

**Comment by kilbith** [comment]
I prefer the good raw .txt format as well for not being polluted by script attributes and "fashion" shallowness.

**Comment by paramat** [comment]
See commit message for https://github.com/minetest/minetest/commit/800d912b6f93b4e9e6efdc89b9e7a720807f2b1a

**Comment by rubenwardy** [comment]
Md/Html formats are much better for sharing links to, without worrying the the line number will change.

However, you could just use [lua_api.html](http://rubenwardy.com/minetest_molding_book/lua_api.html).

**Comment by red-001** [comment]
@kilbith  It is perfectly readable as a text file, most of the changes made a very minor like changing a ' to a \` not anything major.```lua`` appears in the file a few times but that hardly matters to readability.

@paramat I don't think there are a lot of references to `game_api.txt` but that is a good point.

I guess you could always make `game_api.txt` say something like moved to game_api.md.

**Comment by red-001** [comment]
@rubenwardy 'page not found'.

**Comment by red-001** [comment]
@rubenwardy  Is that up to date with lua_api.txt?

**Comment by paramat** [comment]
I find the extra symbols hard on the eyes when viewed as text, i had just got used to lua_api.txt when it was unfortunately changed to MD format, i wish it had not been, a mistake i think. A carefully and cleanly formatted text document would be just as good, the MD format version should be maintained separately by whoever can be bothered to do that.

**Comment by rubenwardy** [comment]
Maintaing two versions is rather silly. Just learn to adapt. I am very glad it was standardised into markdown, makes linking much easier.

**Comment by paramat** [comment]
Yeah i agree 2 versions would be problematic, inevitably one would lag behind and it's more work. So it's a case of what's more important, a friendly document for modders or a a cleaner text document for devs. Difficult choice.

**Comment by paramat** [comment]
Okay with some thought, i'll support markdown format but will never support changing the file extension to .md. Markdown format is meant to be friendly but for a dev the text is preferable, more compact. After looking at lua_api.txt displayed as MD i don't find it an improvement, there's so much space between everything it's actually less clear to me.

I'll +1 this if updated to be formatting only.

**Comment by kilbith** [comment]
> I find the extra symbols hard on the eyes when viewed as text

This is exactly what bother me too.

**Comment by red-001** [comment]
@paramat what do you find decrease the readability as text most?

**Comment by paramat** [comment]
Just the general overuse of special symbols, instead of beng free to make it as clear as possible.

**Comment by 0-afflatus** [comment]
Markdown is for people who find HTML difficult and should only be used in circumstances where the file is not going to be read in the raw. I use text files for my READMEs without the .txt extension. This may be because I have a bad attitude towards Windows users, however.

**Comment by rubenwardy** [comment]
> Markdown is for people who find HTML difficult and should only be used in circumstances where the file is not going to be read in the raw.

Urr, no.

> The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible. The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.

**Comment by 0-afflatus** [comment]
Point taken @rubenwardy - it just doesn't work for me.

**Comment by paramat** [comment]
> The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.

It fails then :)

**Comment by paramat** [comment]
I'll +1 this if updated to be formatting only, please keep it .txt.

**Comment by red-001** [comment]
@paramat  done.

**Comment by paramat** [comment]
Added line comments.

**Comment by rubenwardy** [comment]
I don't think that it fails. I find Markdown easy to read, when it is done correctly. However, some things do suck about it such as it not being very flexible: for example you need to do \```Lua or {% highlight lua %} to highlight the code correctly, and writing custom boxes (eg: warnings) is hard and tends to require HTML insertion.

However, neither of those are required.

I guess it is just personal preference.

**Comment by 0-afflatus** [comment]
> I guess it is just personal preference.

Mostly it is. Whatever approach is taken it needs to be consistent and clear.

**Comment by paramat** [comment]
Will merge once aspen function is added.

**Comment by red-001** [comment]
@paramat done. Added the aspen function.

**Comment by paramat** [comment]
Thanks, but those lines are indented by an extra space compared to the other tree functions.

**Comment by red-001** [comment]
Fixed that.

**Comment by kilbith** [comment]
> Will merge once aspen function is added.

Wait, where is the 2nd approval ?

**Comment by kaeza** [comment]
I'd appreciate if you used indented blocks instead of three backticks to mark fixed-width code blocks. It reduces the line noise for those of us who prefer the plain-text version. The Lua code coloring is mostly useless in this case.

**Comment by paramat** [comment]
I was considering this a trivial documentation update so only needing 1 approval.
Agree with kaeza, please edit.

**Comment by rubenwardy** [comment]
I'd prefer it if you put a space above and below headings like this:

```
one

Heading
======

two
```

**Comment by kilbith** [comment]
This is nothing but trivial. This is a major formatting change.

**Comment by rubenwardy** [comment]
Trivial means that it can't possible cause errors or bugs, or in the case of documentation misinformation. Therefore this is, imo, trivial.

**Comment by kilbith** [comment]
No absolutely not. You're twisting that definition on purpose. A major formatting change must get 2 formal approvals in the sense it can affect the user-land quite importantly.

**Comment by red-001** [comment]
@kaeza @paramat  removed the ```lua.

**Comment by red-001** [comment]
@rubenwardy  added extra spaces.

**Comment by paramat** [comment]
Lines 261-294 seem to have inconsistent indentations of comments and varying number of spaces after the asterisks.

I agree this is borderline non-trivial but due to elusive mtgame devs i'm happy to take the risk.
However extra input is good so @sfan5 @Ekdohibs @PilzAdam @ShadowNinja

**Comment by paramat** [comment]
Also the indentation in the dyes section is inconsistent.

**Comment by sofar** [comment]
The doors API patch is not yet merged, so this will conflict. I have various style fixes pending in the PR there, and will refresh that one depending on what gets merged first.

**Comment by paramat** [comment]
This may need rebasing due to fences API being added.

**Comment by sofar** [comment]
@paramat I prefer seeing patches merge quicker than attempting to choreograph a dance around dependencies, especially when it comes to documentation which shouldn't gate or be gated by anything.

**Comment by paramat** [comment]
Agreed, it may not conflict.
Inconsistencies still need editing.

**Comment by paramat** [comment]
^ @red-001

**Comment by paramat** [comment]
This may need to be worked on by someone else as the author is absent.

**Comment by red-001** [comment]
I'm back.

**Comment by paramat** [comment]
Welcome back.

**Comment by paramat** [comment]
Lines 77, 283, 285, 290: Should be 1 space after '*' not 2.
Lines 371 to 400: Please indent all the lines starting with '*' by 1 more space to be consstent with the rest of the file.

**Comment by sofar** [comment]
Still needs rebasing.

**Comment by red-001** [comment]
@sofar  Rebased.

**Comment by paramat** [comment]
Lines 28, 29, 37, 61: One less tab indent.
Lines 35, 36 and 50 to 58: Align comments vertically using spaces.
Line 83: No space after first curly bracket.
Line 103: No spaces inside curly brackets.
Line 116: Should be 'tile_side = ""'
Line 139: 'choppy = 2'

Please add the new tree function:
default.grow_new_snowy_pine_tree(pos)
'Grows a new design snowy pine tree at pos'

**Comment by paramat** [comment]
^ @red-001

**Comment by red-001** [comment]
@paramat Updated.

**Comment by paramat** [comment]
:+1: Will merge soon as trivial.

**Comment by paramat** [comment]
68f5740dcc5ae16f6506f773894768f7d19c60e8

**Pull request closed without merging**
