### PR TITLE
Textures Update

### PR DESCRIPTION
**Pull request by kilbith2**
Most of textures comes from the PixelBOX texture pack by Gambit and are licensed under WTFPL : http://forum.freeminer.org/threads/16x-pixelbox.131/

Notes : 
- Except for the farming textures, I've slightly modified the textures or completely changed their colors/contrast.
- As Mese is alien stuff, the latin characters "MESE" on the previous texture were inappropriate. So I changed for a "mysterious" scripture on the block. Also, the current crystal shape is too close from a classical representation of diamond.
- Same ingots/brick/rails patterns with better coloring.

EDIT : farming textures updated, see comments below.

Before / After : 

screenie_old
screenie_new

---

Before / After : 

old
new

---

Complete farming stages : 

Old : https://lut.im/tfvgY971/CjAnHcJ4
New : https://lut.im/MdzCpqPV/GaVuhEF7

### CODE REVIEW

**Comment by Heybye44** [comment]
:+1:

**Comment by MT-Modder** [comment]
:+1:

**Comment by RHRhino** [comment]
PixelBOX is great, but please also add a picture which shows all stages of wheat and cotton growing.

**Comment by kilbith2** [comment]
I just added the farming stages images in 1st comment.

**Comment by PilzAdam** [comment]
You forgot to delete some of the textures from the lists of other authors (e.g. default_book.png is listed twice now).
Mese is not "alien stuff".
The full grown wheat looks too "thin" to me.
Cotton looks too dry.
The new cotton seeds are better, since you can see the number in the bottom right easier now.
I don't see how the new book is "better"; it's just different.

**Comment by kilbith2** [comment]
Google Images results : 

- For the wheat : http://tinyurl.com/odgryky
- For the cotton plant : http://tinyurl.com/kom4g4c

... that's seems realistic, right ? :)

**Comment by 0-afflatus** [comment]
The wheat is too green. It should ripen to a pale golden colour. 
I have never seen a cotton plant in rl, but it seems the original dark brown stems with darker green leaves is a better colour.
Sample the colours and compare hex values.

**Comment by 0-afflatus** [comment]
The seeds are a definite improvement and the the ore nuggets are getting there.

**Comment by kilbith** [comment]
> Mese is not "alien stuff".

http://irc.minetest.ru/minetest-dev/2012-12-13#i_2711799

**Comment by PilzAdam** [comment]
@kilbith How is that relevant? It's just one of many ideas that c55 listed and he said it was a bad idea. Also no decision was made, so mese isn't alien stuff.

**Comment by paramat** [comment]
Mese is indeed 'possibly of alien origin'.
In my opinion:
Our current mese texture is really bad, this one is a huge improvement, the alien-looking font is a good idea that occured to me too, i was actually about to submit my own mese texture (and probably still will).
The stages of wheat are good but the final stage colour is too yellow-green instead of golden.
The cotton may be more realistic but is dull and lacking contrast and brightness, a bit dark and depressing like our current grass texture is. Minetest textures have, and need, a slightly abstract and 'cute' character.
The new item textures are good.

**Comment by kilbith** [comment]
@PilzAdam He (c55) wanted something "unfamiliar" or fantasist for the Mese. So my logic was to break up the latin characters to be faithful with the spirit of the Mese block (defined by c55), and give it an "aura of mystery".

Also, Mese as alien stuff is in the popular culture, (unofficially ?) stated by some well-known modders according to my reading.

But if you just don't like my texture, just tell me - that'd be enough and straightforward to the point :)

**Comment by paramat** [comment]
^ Yep, that's why my meteor mod is lumps of mese falling from above, it has acquired a space/alien character in MT culture.

**Comment by kilbith** [comment]
So I re-worked the stages 7 & 8 for the cotton (darker wood w/ leaves) and wheat (more golden). Tell me if you like or not...

EDIT : cotton stage 8 updated, see comment below.

new2

**Comment by MT-Modder** [comment]
:+1: I think they look better.

**Comment by ShadowNinja** [comment]
:+1:

**Comment by kilbith** [comment]
Improved again the stage 8 textures... I think I'm done with it now.

EDIT : screenie deleted. See comment below.

**Comment by RHRhino** [comment]
IMO the wheat texture is too much saturated (stage 8) and has to many white dots in it (all stages) but the cotton looks nice. The color shift of the cotton textures is great. I think it would look better if you could make use of this on the wheat texture too, by coloring the darker areas in an orange-brownish color and the lighter areas in a yellow-golden color. It's definitely worth a try. :smile:

**Comment by Heybye44** [comment]
:+1:



—

**Comment by kilbith** [comment]
Wheat update, all stages : 
- stage 8 with orange-brownish bottom and less saturation overall (natural golden).
- less bright dots (although they're importants for the contrast).
- tweaking on colors for consistent evolution.

I hope you're all satisfied now...

new2
new

**Comment by RHRhino** [comment]
Well done! I love them! :+1:

**Comment by MT-Modder** [comment]
:+1: I love them as well, great work @kilbith.

**Comment by 0-afflatus** [comment]
Right, I want to see it in action now.

**Comment by Novatux** [comment]
Looks good

**Comment by sfan5** [comment]
:+1:
*except*:
* The ingot textures are fine already (brick, copper, bronze, iron, gold)
* The old mese texture should be kept because it's something special

**Comment by kilbith** [comment]
@sfan5: done.

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/5518c277f31800d407ddf2af8b64e532a85f7533

**Comment by paramat** [comment]
I am satisfied =) beautiful textures.

**Pull request closed without merging**
