### PR TITLE
Optimize Sam II + textures

### PR DESCRIPTION
**Pull request by kilbith2**
Similar model, optimized : **316 KB** (.x) ⇒ **85 KB** (.b3d).

### CODE REVIEW

**Comment by kilbith** [comment]
Also, optimized the textures (~150 KB less).

**Comment by C1ffisme** [comment]
I think there are some problems with your pull request. It looks like you deleted everything and re-added it. This happened to me with my pull request. Try doing this again, but clone minetest, edit it and then push it to your repository.

**Comment by Novatux** [comment]
@C1ffisme: no, this is because he optimized the textures.
What is the relative size reduction?

**Comment by SmallJoker** [comment]
How did you optimize the textures? OptiPNG / PNGcrush?

**Comment by kilbith2** [comment]
As I deleted the useless "alternates" folder in the vessels mod, @sfan5 wanted to conserve them **especially** without a legit reason whereas no others textures benefit of alternatives. Such absurdity leads me to close the PR.

**Comment by ShadowNinja** [comment]
Still usable.

**Comment by kilbith2** [comment]
http://irc.minetest.ru/minetest-dev/2015-02-01#i_4137678

I'm just pissed off by that stupidity, therefore it won't be merged.

**Comment by PilzAdam** [comment]
@kilbith2 yes, this is weird, but why close this pull request for it?

**Comment by kilbith** [comment]
@PilzAdam : if I don't let this 'alternates' folder, the PR won't be merged - sfan5's wish & decree.

I'm heatedly opposed to keep this silly folder.

**Comment by PilzAdam** [comment]
@kilbith Is it the main purpose of this pull request to remove that folder? Protip: It isn't.

**Comment by VanessaE** [comment]
Although they're not directly related to the original purpose of this pull request, it's safe to remove those "alternate" textures.  Originally I put them there as optional files for wield-versus-inventory imagery, before figuring out that texture alpha works in the inventory, and then things got moved around.  They're obsolete now.

**Comment by HybridDog** [comment]
@kilbith @kilbith2 if you want to stop this, don't close the pull request, remove your master branch

There's a ~30 Kb header.png:
header

**Comment by kilbith** [comment]
@HybridDog : your header is not good, you have removed the alpha channel (transparent background).

**Comment by HybridDog** [comment]
>your header is not good, you have removed the alpha channel (transparent background)

oh, sorry, l forgot that jpg doesn't support alpha

**Comment by BlockMen** [comment]
f86ac2fdffba76621935e2ea62038107f5269daf

**Pull request closed without merging**
