### PR TITLE
change mineral textures

### PR DESCRIPTION
**Pull request by HybridDog**
change mineral textures

### CODE REVIEW

**Comment by paramat** [comment]
Don't worry about providing normalmaps, they are complex to make and apparently need to be high resolution (gimp has a filter to create normalmaps from textures).
Please can you post before / after screenshots?

**Comment by paramat** [comment]
These seem to be the ones from #313, the coal is okay, diamond and gold are excellent. Copper needs editing as it has messy use of alpha around the edges, perhaps you could remove the translucent pixels and make it shinier and more metallic, in the way diamond and gold are?

**Comment by kilbith** [comment]
This is total BS...

The ores aren't supposed to be overloaded in stone like that. Rather discreetly inlaid to blend well within the stonish environment and not being too "showy" to the eyes of the heedful miners.

Look at PixelBOX for examples.

**Comment by HybridDog** [comment]
>I feel coal and copper need editing as they have messy use of alpha around the edges, perhaps you could remove the translucent pixels?

l actually wanted to make a smooth transition between mineral and stone texture.
>Please can copper be shinier and more metallic, in the way diamond and gold are?

l would rather like shaders to do reflections.
>The ores aren't supposed to be overloaded in stone like that. Rather discreetly inlaid to blend well within the stonish environment and not being too "showy" to the eyes of the heedful miners.

sorry, maybe l made it unknowingly to get more success in mining

**Comment by paramat** [comment]
Okay no problem. I don't like the use of alpha to blend, so my opinion is to use the diamond and gold textures only. If HybridDog and other devs are okay with this i can make a new PR.

**Comment by HybridDog** [comment]
the gold maybe has too much saturation

**Comment by paramat** [comment]
Gold and Diamond look good to me, if you open a new PR with those 2 i will +1.

**Comment by HybridDog** [comment]
The diamond texture is from the diamonds mod. l think minetest took its diamond textures from an old version of the mod.

**Comment by kilbith** [comment]
From [Cisoun's Texture Pack](https://forum.minetest.net/viewtopic.php?id=16) (WTFPL) - gold texture : 

capture d ecran_2015-09-21_21-35-17 default_gold

**Pull request closed without merging**
