### PR TITLE
Add a separate image for a written book.

### PR DESCRIPTION
**Pull request by sofar**
Since written books are quite different from empty books, the
visual clue that they are different items is really needed in-game.

I've added a "clasp" or "belt-with-buckle" like element to the
png from default_book, keeping them very similar but also
immediately recgnizably different.

I added the new texture to blockmen's license list since it's
obviously derivative of his work.

The PNG was run through a minimizer/optimizer to save space.

### CODE REVIEW

**Comment by kilbith** [comment]
LGTM.

**Comment by BlockMen** [comment]
@sofar you should use Minetest NeXt, long time done there https://github.com/BlockMen/minetest_next/commit/07092f84a7ae4e73f09e9776d3294c3d87bfe560 :P

And no need to give me the credit, since its your work. Adding a note like derived from ... is enough.

**Comment by sofar** [comment]
@BlockMen stuff like this should go back into upstream way, way more rapidly.

**Comment by BlockMen** [comment]
@sofar Minetest NeXt is GPL 3.0, not LGPL. And I forked minetest_game for some reasons, so i won't merge anything back ;)

**Comment by sofar** [comment]
Please, if your fork isn't able to merge back, then you're just trolling in this thread. Go away.

**Comment by BlockMen** [comment]
Trolling is by definition aiming for an emotional response of readers, my post is clearly not. Interesting is indeed that you do react emotional on this. Offering (you) an alternative to minetest_game is neither provoking emotions nor invalid / unpolite behavior.

**Comment by sofar** [comment]
It does not help, and certainly distracts the discussion here, which has clearly not evoked a positive reaction in me.

**Comment by 0-afflatus** [comment]
@BlockMen give it a rest.
Minetest Game is supposed to be minimalistic and conservative. It is completely natural for concepts to be tried and tested in sub-games and the most stable ideas filtered through to the flagship game. 

As sub-game designers our only interest here is whether we need to add this idea to our own games. You already have, well done. Which all goes to prove it's a good idea.

:+1:

**Comment by BlockMen** [comment]
> Minetest Game is supposed to be minimalistic and conservative.

>  filtered through to the flagship game.

@0-afflatus a "flagship" game is kinda the opposite of minetest_game. Just the fact that it is located under the minetest organisation on github doesn't it make a good or stable game, which is intention of "flagship" things.

**Comment by paramat** [comment]
:+1: Good idea. And yes you should credit yourself for the image as it's very different from BlockMen's.

**Comment by 0-afflatus** [comment]
I seriously find it useful to think in terms of "blame" when assigning credits, rather than "kudos"; as in - who should the user complain to if they don't like it.

**Comment by sofar** [comment]
Changed attribution to list me with a backref to origin.

**Comment by sfan5** [comment]
b57ecb94df2bfc1c6383a3d35465e22b683821ee

**Pull request closed without merging**
