### PR TITLE
Boats: Optimize, re-UV unwrap.

### PR DESCRIPTION
**Pull request by sofar**
The boat model had over 1700 tris (!) before this redo. I've reduced
the amount of tris to ~150, which is very reasonable given that there
are almost 45 faces to this model.

I've also spent a good hour re-UV unwrapping the entire model which
has a huuuge impact on the boats' appearance. As much as possible,
the boat now looks like it's made out of actual blocks of wood,
and I've even attempted to make the grains connect around edges,
appear in the same pattern and spacing, and generally make it look
like it's just a nice crafted thing out of several pieces of wood.

I've had to tweak the rudder part to make the texture actually have
square texture pixels. I did that by varying the vertical position of
the botton of the rudder handle and the top of the rudder bottom, which
worked well. I also had to 'slice' the rear face of the boat to prevent
a strange texture tear, probably due to non-flat surface somewhere,
but I couldn't spot the issue there anymore after adding 2 extra edges.

This looks totally like a new boat now.

### CODE REVIEW

**Comment by sofar** [comment]
@PilzAdam

**Comment by sofar** [comment]
mmm rudder is still off side-by-side compared. Needs one more tweak.

**Comment by sofar** [comment]
Fixed up rudder one last time and I'm calling it good.

**Comment by Rui914** [comment]
\>image
It seems that wood texture.
But, this PR doesn't update texture.
Why?

**Comment by kilbith** [comment]
Nice improvement :+1: 

> I'm adding the blend file for the boat. I believe we should try to
> make an effort to make modding easier by having blend source files
> for objects in the game as they facilitate fixing these models.

I'm against. The Blender files are heavy and you can already import the .obj models quite easily.

**Comment by Fixer-007** [comment]
Looks nice, I like it.

**Comment by PilzAdam** [comment]
:+1: (I haven't tested this in-game, though)

**Comment by sofar** [comment]
@kilbith I took it out already again.

**Comment by sofar** [comment]
@Rui914 

the boat used, and uses, ```default_wood.png``` as texture. By UV unwrapping the mesh from scratch, I was able to use the existing texture in a much better way than before, without changing the texture.

**Comment by NathanSalapat** [comment]
OBJs are easy enough to import, though it's still easier to use the .blend, but agree, that the .blend isn't needed for this. If we were talking about b3d I'd say keep the .blend.

**Comment by paramat** [comment]
Will test and possibly merge later.

**Comment by paramat** [comment]
1977ae19ae9883b6039bf330d705e8e582ee6387

**Pull request closed without merging**
