### PR TITLE
Check inventory in boat.on_punch

### PR DESCRIPTION
**Pull request by ghost**
If puncher inventory is full, then drop boat.

### CODE REVIEW

**Comment by LeMagnesium** [comment]
The code looks fine, I see no visible mistake. The only thing I noticed is that the end line was removed but I don't remember whether GitHub hides it or not, there was an issue like that.

**Comment by paramat** [comment]
+1 seems good.

**Comment by kilbith** [comment]
A bit of attention to this PR please.

**Comment by paramat** [comment]
Approval http://irc.minetest.ru/minetest-dev/2015-10-18#i_4427005

**Comment by paramat** [comment]
Sorry we took a long time on this, needs rebasing now.

**Comment by kilbith** [comment]
Seriously, for 6 lines to add ? ...

**Comment by PilzAdam** [comment]
@paramat umm... no, it doesn't.

**Comment by paramat** [comment]
I agree it doesn't seem to have conflicts, but when i tried to merge it refused and notified about conflicts. I'll open a new PR for this and do it myself since it's simple.

**Comment by paramat** [comment]
New PR #711

**Comment by paramat** [comment]
Merged f3dc78204c83e55363bcdfe40b31b33949e198a7

**Pull request closed without merging**
