### PR TITLE
Add Backgrounds for Formspecs

### PR DESCRIPTION
**Pull request by C1ffisme**
Sorry for a few minor pull request problems. I have gotten it, this time.

The idea is to **add a way for texture packs to change the backgrounds of formspecs** and to **make minetest look a LOT better to gamers**. Now, this pull request provides backgrounds I have made. **They look bad.** I am not going to merge them in the final version. However, I will accept background that **you can make, and post in the comments below**. Those will be added to the pull, and the community can decide how they like them.

Rules for creating backgrounds : 
- Must be a free license
- Must be a cultural license
- Must be appropriate for all ages (IDK how you break this one, but I suppose it's possible)
- Must follow minetest's style.

### CODE REVIEW

**Comment by PilzAdam** [comment]
Opening a pull request to request others to create textures isn't really a good way. This PR won't get merged as it is and people who want to create texture most likely don't look at PRs when deciding what to do.

**Comment by kilbith** [comment]
@C1ffisme Again : GitHub isn't a forum or chit-chat place for suit your recurring offtopic/nonsense in comments and those successions of noisy "BUMP!" in the whole depot.

**Comment by C1ffisme** [comment]
@kilbith I'm not just chit-chating. This pull adds an actual feature that people may want. Also, where did I put any offtopic comments? And the bumps are to make people see the old posts. Because unfortunately, people tend to look at only the newest of pulls, and sometimes old pulls or bugs that scar minetest or are really wanted fixed/added are stuck unseen. I want to add a feature that allows players to do something wanted by many asthetic people, and texture pack makers. However, I suck at making textures, and I want other people to post.

The reason I remade this pull request, if you must know, is because I made the last one wrongly.

@PilzAdam True, but when you have the code, you might as well. Can you see another option to help texture pack makers? And don't say they can just mod, because some people cannot code and can only make textures. Why did we make the grass side texture with transparency? Because we wanted texture pack makers to have an easier time.
> This PR won't get merged as it is...
That isn't what you alone decide. Other people may have an opinion.
> ...and people who want to create texture most likely don't look at PRs when deciding what to do.
They don't decide to make textures, they can come here and see that someone needs help, and then help by posting their own textures.

Github is a place for conglomeration and cooperation. A pull request is a way to help, and so is posting your textures. So we are all helping each other with this pull.

**Comment by thatgraemeguy** [comment]
A pull request isn't a discussion ground. Its a way to say "hey, I have made some changes that are working well and ready to be integrated with the existing code".

**Comment by PilzAdam** [comment]
@C1ffisme ask in the forums. Github is mostly used for sharing code, so not many artists care to look at PRs.

**Comment by C1ffisme** [comment]
Ah... One of these days I'll find myself getting a forum account. Eventually, PilzAdam.

**Comment by paramat** [comment]
This PR is going nowhere fast.

**Comment by 0-afflatus** [comment]
@C1ffisme 
> One of these days I'll find myself getting a forum account.
^ That ^ would be a great idea. 
I think you'd get a much more positive response if you moved the longer discussions over there.

**Comment by C1ffisme** [comment]
I'm going to be removing my repo soon...

**Pull request closed without merging**
