### PR TITLE
Creative: Rename fields with correct naming convention to avoid possible conflicts

### PR DESCRIPTION
**Pull request by kilbith**
Some item from an external mod could set e.g. `search` as field in its formspec and use it for filtering the creative inventory by inadvertence.

### CODE REVIEW

**Comment by rubenwardy** [comment]
A better fix would be to check that formname == "" here: https://github.com/kilbith/minetest_game/blob/master/mods/creative/init.lua#L161

**Comment by rubenwardy** [comment]
A better fix would be to check that formname == "" here: https://github.com/kilbith/minetest_game/blob/master/mods/creative/init.lua#L161
However renaming to creative_* makes sense for consistency

**Comment by kilbith** [comment]
I already thought to that, however lot of mods pass `""` in 2nd parameter of `minetest.show_formspec`.

**Comment by rubenwardy** [comment]
They definitely shouldn't do that.

Maybe do both of those things?

**Comment by kilbith** [comment]
You're right, it increases the robustness.

**Comment by paramat** [comment]
:+1:

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.ru/minetest-dev/2016-02-21#i_4540419

**Comment by kilbith** [comment]
Renamed one remaining field, and slightly simplified some Lua patterns for reducing their greed.

Now ready for merge.

**Comment by paramat** [comment]
4c9944b263d31a8511a252f758e1bedf28559f7a

**Pull request closed without merging**
