### PR TITLE
Optimize boat model (.x -> .obj)

### PR DESCRIPTION
**Pull request by kilbith2**
.x format is not necessary since the model is not animated. The new file (.obj) is 300 KB lighter and the appearance is unchanged.

### CODE REVIEW

**Comment by paramat** [comment]
+1 good idea.

**Comment by C1ffisme** [comment]
:+1:

**Comment by Novatux** [comment]
Looks good

**Comment by sfan5** [comment]
Wouldn't .b3d be even smaller?

**Comment by Jordach** [comment]
It would - and it's also a proprietary format in binary.

**Comment by kilbith** [comment]
@sfan5 @Jordach No I tested earlier : ~160 KB.

B3D excels for the animated models. Not the static ones.

**Comment by PilzAdam** [comment]
:+1:

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/9eb9502209b33bed33a36fb3db2ab4a59716fe5b

**Pull request closed without merging**
