### PR TITLE
short code in crafting.lua, make it easier to read and fix quotes

### PR DESCRIPTION
**Pull request by HybridDog**
It's a lot easier to read and understand because you don't need to read code repeating itself

### CODE REVIEW

**Comment by C1ffisme** [comment]
Good idea. :+1:

**Comment by HybridDog** [comment]
thanks

**Comment by kaeza** [comment]
:+1:

**Comment by MoNTE48** [comment]
:+1: good work!

**Comment by sofar** [comment]
How does it make it easier to fix quotes?

I'd say this makes the code harder to read, not easier, since the shorter code now is more complex than it was before.

It does *reduce* the amount of code, which is a good thing.

**Comment by 0-afflatus** [comment]
It probably is better coding style, but I don't think it makes the code easier to read and understand.

**Comment by HybridDog** [comment]
You don't need to scroll so much, e.g. if you want to know the furnace burntime of 3 specific fuel items, you just need to take a look at that list instead of scrolling through many lines of codes.
https://github.com/minetest/minetest_game/pull/841/files#diff-2c5094a7e6e2fa054c2eeeec6e8362b7R308


>How does it make it easier to fix quotes?

fix quotes doesn't refer to making it easier, else the comma after crafting.lua would be an and

**Comment by sofar** [comment]
ahhhh, hahaha. Now I get it.

You should really try to get your punctuation correct.

I read the title as:

```makes it easier to (fix quotes && read)```

Instead, you should have written something like:

```
Clean up code in crafting.lua

- Make quote style uniform
- reduce tedious recipe code repetition with table that are easier to read
```

Your commit message will be part of the repository after it merges, please treat it with the same carefulness as you treat the code.

**Comment by paramat** [comment]
:-1:

**Comment by kilbith** [comment]
:-1: Does not make Minetest any better. You can also use Ctrl+F and quickly search.

**Comment by rubenwardy** [comment]
:+1: for double quotes

**Pull request closed without merging**
