### PR TITLE
Optimize all sounds

### PR DESCRIPTION
**Pull request by kilbith**
Same length durations, optimized : `519 KB` -> `379 KB` (140 KB less).

### CODE REVIEW

**Comment by Calinou** [comment]
What software did you use to optimize sounds? Did you just reduce their bitrate?

**Comment by kilbith** [comment]
> What software did you use to optimize sounds?

Audacity.

>  Or did you just reduce their bitrate?

Their bitrate is exactly the same.

**Comment by tenplus1** [comment]
Lossy format being converted back to lossy format will indeed be smaller because some of the audio quality has been reduced further...

**Comment by kilbith** [comment]
You would not notice a quality loss. Please test and compare before any comment.

**Comment by sfan5** [comment]
IMO a small size reduction like this does not warrant the quality loss caused by re-encoding lossy sources.

**Comment by kilbith** [comment]
no interest, closing.

**Comment by HybridDog** [comment]
l would like a setting in minetest which disables sound preloading (only works in singleplayer mode).

**Pull request closed without merging**
