### PR TITLE
Add new texture for default:leaves and style simple

### PR DESCRIPTION
**Pull request by RealBadAngel**
Texture is a bit more dense, used only when leaves_style = simple
screenshot_20150708_225950
screenshot_20150708_230001

### CODE REVIEW

**Comment by paramat** [comment]
Please can you add a screenshot?
The dense texture could possibly be used for opaque also, to minimise the dark gaps.

**Comment by paramat** [comment]
The sandstone brick normalmap shouldn't be here =)

**Comment by kilbith** [comment]
@paramat If you want dense leaves, there are really nice ones in PixelBOX.

**Comment by paramat** [comment]
Well i find however dense the texture is, even with just a few single-pixel gaps, it is still obvious there is a big empty space inside a tree, which looks wrong to me. Fancy leaves are only just dense enough an effect for me. Although it may be acceptable to some, i think glasslike leaves just doesn't work and was rather hastily merged when many devs find it ugly, it is also a pain having to have 2 sets of textures for any leaf node.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Anyway, since we now have simple leaves, the denser textures are needed, +1.

**Comment by paramat** [comment]
0c5f6dabc03fe4078211d9dc165657eb51451105

**Pull request closed without merging**
