### PR TITLE
Default: Add savanna nodes, crafting and fuels

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150711_222638

^ With fancy leaves option.

Savanna is essential to the biome system of mgv5/mgv7 and has been added, these are the new nodes, the first step to adding the full biome system in time for 0.4.13.
I have named these 'dry grass' instead of 'savanna grass' because Minetest nodes are best being flexible for many uses, also the word 'dry' is nice and short.

'dirt with dry grass' has a louder footstep sound.
'dirt with dry grass' is added to the grass->dirt ABM and drops dirt.
I simplified fuel definitions by using 'group:sapling' instead of individual definitions.
'dry grass 1' is defined as a fuel.
Credits in README have been updated, with also a correction for default_grass_\* and with Gambit's credits moved to before the sounds credits.

In nodes.lua:
Some left over mistakes i made when adding pine nodes have been fixed, and pine sapling now has 'sunlight propagates = true', which was missing in a recent commit. Some lines are shortened and missing spaces added.

screenshot_20150711_223746

^ The background becomes dark green instead of black when opaque leaves are used.

### CODE REVIEW

**Comment by kilbith** [comment]
:+1: much better for the savanna's ground texture.

EDIT : texture fixed.

**Comment by paramat** [comment]
Thanks, silly mistake, will fix.

**Comment by paramat** [comment]
Fixed.
It's weird, somehow i copied VanessaE's 3-division pull request wood texture and derived my mapgen mod pine wood and acacia wood from it.

**Comment by asl97** [comment]
i think it's just me but that leaves look weird (and scary at first look),  most likely cause it look unnatural.

**Comment by C1ffisme** [comment]
@asl97 Actually, they look really awful to me too. They almost look more like microchips than leaves. They need a more organic feel to them, currently they look more like pixel art.

**Comment by est31** [comment]
Perhaps the acacia sapling should get a more different sapling image than the pine sapling.

**Comment by est31** [comment]
Like the dungeon mapgen bug showing in the upper right corner :)

**Comment by paramat** [comment]
> Perhaps the acacia sapling should get a more different sapling image than the pine sapling.

It is a recoloured pine sapling, much like the jungle sapling being a recoloured appletree sapling. Not a big problem, perhaps in time someone else will make new individual textures for jungle sapling and acacia sapling.

I did expect the leaves being a little unpopular =) but i spent hours looking at acacia photos and these are accurate in having fern-like fronds of tiny leaves between big, scary light-brown thorns. I may well work on it a bit to make it a little more varied and organic. Also i have fancy leaves off here so they appear more striking against black, i should also adjust the background to very dark green for when fancy leaves are off.

At centre-top there is a large dungeon room hanging off the side of the mountain.

I will make 'dirt with dry grass' drop dirt, and add it to the ABM that turns grass to dirt in dark places. At first i left these out of the PR to avoid dirt regrowing green grass in savanna, but consistency is more important. Some fresh green grass in savanna is not a problem.

**Comment by est31** [comment]
About the leaves: well its a blocky game. As long as it doesnt look like a kilt or a nazi symbol, its ok IMO.

**Comment by paramat** [comment]
My intention is to get the biome system, and these nodes and textures, merged for 0.4.13 in an initial unstable state, then refine everything during 0.4.13. So there's no time to get everything perfect beforehand. Anyway i will work on the leaves texture, perhaps make the fronds and thorns a little smaller and have more of them, to be more consistent with our other leaf textures, and more life-size. But i need the new nodes in soon, in a few days, to then get the biome system in.

**Comment by est31** [comment]
ok to the sapling texture. I've tried to improve it, but failed. Seems I'll have to live with it now, and it already works for jungle sapling, why not acacia too.

**Comment by nerzhul** [comment]
@paramat i think, due to many and many changes, if i get time to implement enet and new session system in next weeks , we should call it 0.5.0, there are many new features and rework

**Comment by paramat** [comment]
I was tired yesterday and made many mistakes, now fixed, also:

'dirt with dry grass' is added to the grass->dirt ABM and drops dirt.
I simplified fuel definitions by using 'group:sapling' instead of individual definitions.
Some left over mistakes i made when adding pine nodes have been fixed, and pine sapling now has 'sunlight propagates = true', which was missing in a recent commit.
Some lines are shortened and missing spaces added.

Now i intend to redo the leaves texture before this is merged.

**Comment by Megaf** [comment]
:+1:

**Comment by RealBadAngel** [comment]
man, those leaves are ugly :)

**Comment by paramat** [comment]
Yes new texture will have dark green gaps.
L-system is too slow for mapgen.

**Comment by paramat** [comment]
New leaves texture, texture credits added, first post updated, this seems ready to go.

**Comment by Novatux** [comment]
Looks good !

**Comment by paramat** [comment]
I'll push this later.

**Comment by paramat** [comment]
6843ddb814fe71147ec86728018e99ad75ab243a

**Pull request closed without merging**
