### PR TITLE
Destroy items when they touch lava or fire

### PR DESCRIPTION
**Pull request by Calinou**
Work in progress, no sounds yet.

_Code by kilbith._

### CODE REVIEW

**Comment by RHRhino** [comment]
Hmm it would even more interesting if people who die drop all their items, if they disabled the bones mod ...

**Comment by paramat** [comment]
If the check is done every server step: i think better to have a low chance random check to be lightweight, items don't need to be destroyed immediately, better they take a random length of time to be destroyed.

**Comment by kilbith** [comment]
I think it'd be best to refresh and merge [builtin_item](https://github.com/PilzAdam/builtin_item) by @PilzAdam into the engine. It has a time setting delaying the object clear-out.

**Comment by tenplus1** [comment]
RHRhino: try these 2 mods:
https://github.com/tenplus1/builtin_item
https://github.com/tenplus1/dropondie

**Comment by RHRhino** [comment]
Thank you very much tenplus, but I already use them together with item_drop. :smile: 

I just think it would be more challenging if people loose their items when they die in lava and the items could get destroyed there.

**Comment by HybridDog** [comment]
you also need to add particles and sounds

https://github.com/HybridDog/builtin_item/blob/master/init.lua#L111

**Comment by C1ffisme** [comment]
This would be an extremely useful feature... It also means people are going to have to start acting careful around lava, though.

**Comment by HybridDog** [comment]
>It also means people are going to have to start acting careful around lava, though.

especially if they're stuck in nodes because then the items become dropped instead of put into bones

**Comment by nerzhul** [comment]
:+1:

**Comment by kilbith** [comment]
Let's discuss about that again.

**Comment by PilzAdam** [comment]
I like this. Maybe let the time it takes to burn the item depend on the group rating? That way items will last a bit longer while lying in fire, and will almost instantly disappear in lava.

**Comment by ShadowNinja** [comment]
An extension of PilzAdams suggestion: make only flamable items burn, make inflamible items take much longer to burn, or make them only burn when the heat source is intense enough.

**Comment by Ekdohibs** [comment]
I like this too; extending on ShadowNinja's suggestion, item definitions could have an optional field that would allow to control the burn time and would be calculated depending on whether the item is flammable if that field is missing.

**Comment by kaeza** [comment]
:+1:

But maybe choose another group in addition to `igniter`. For example, some items may be destroyed by lava, but not by fire.

**Comment by sofar** [comment]
You can track progress in the top comment  with ```- [ ] item not done``` strings, may be useful in here to summarize the discussion.

I like where this is headed, but there's no code progress.

**Comment by Fixer-007** [comment]
+1

**Comment by paramat** [comment]
@Calinou any progress?

**Comment by kilbith** [comment]
I coded this and asked Calinou to open this PR for me.

I'll probably open my own PR soon or leave @PilzAdam to import his code from builtin_item.

**Comment by paramat** [comment]
@Calinou ANy progress?

**Comment by C1ffisme** [comment]
Maybe certain tools and items should have a group "unburnable" just for the purpose of another advantage of that tool or item.

For example, an obsidian pickaxe might have low speed, but doesn't burn in lava, so that using it to mine obsidian is a good idea. (If the server uses dropping on death.)

**Comment by Fixer-007** [comment]
Actually Calinou told me to close this on #minetest somewhere 6 days ago.

**Comment by paramat** [comment]
Anyone want to take this over? It seems to need reworking.

**Comment by Ferk** [comment]
I submitted an alternate implementation: #1285

Btw, [PilzAdam's builtin_item](https://github.com/PilzAdam/builtin_item) doesn't really use a timer or delay when checking the node, the only timer used there is equivalent to the "age" value that is already in builtin for removing the item after a (custom) long time has passed. Nothing to do with burning the item.

**Comment by paramat** [comment]
Closing as we have a new submission, and on author's request.

**Pull request closed without merging**
