### PR TITLE
Obsidian Glass Panes

### PR DESCRIPTION
**Pull request by ghost**
This adds obsidian glass panes to minetest_game.

### CODE REVIEW

**Comment by kilbith** [comment]
Please GTFO and learn git and basic Lua programming. :-1:

**Comment by MT-Modder** [comment]
Yeah...too many unrelated/unneeded changes relative to just adding the new pane. Try to keep pull requests to 1 commit, unless it's such a big change it's worth splitting up, which is rare. Either learn to squish your commits or open a new PR, although the latter isn't really recommended if you know how to squish.

I like the idea though.
Best of luck to you.

**Comment by C1ffisme** [comment]
From a gameplay wise perspective, do we really want obsidian glass panes? I use glass panes for almost everything, and this might make the normal ones almost useless.

**Comment by MT-Modder** [comment]
I think it's mainly personal preference but if they were made inflammable then that would be a plus.

**Comment by C1ffisme** [comment]
> but if they were made inflammable

Are the normal ones flammable? I was not aware of this.

**Comment by MT-Modder** [comment]
Actually I'm not sure, probably not. It could have been a mod I used to use: "fire_plus".

I think they should be though.

**Comment by DonBatman** [comment]
I would rather see glass drop as items.

**Comment by sofar** [comment]
The proper term is to ```squash``` commits.

In this case, however, I would recommend retracting this commit, and redoing it from scratch. The addition of a new xpane type should be a single block of changes 10 lines long or so, not touch code all over the place.

**Comment by MT-Modder** [comment]
@sofar Thanks. You can tell I've never learned to used it. XD

**Comment by paramat** [comment]
@BBmine We can squash commits on merge, but please add proper commit messages.
You might want to wait to see if we merge #946 first, which because of it's quality is higher priority.

**Comment by BBmine** [comment]
@paramat I edited the init.lua and added a proper commit message.

**Comment by paramat** [comment]
#946 is very likely to go ahead. Closing this because the PR will need a complete rework, and due to code issues.

**Comment by BBmine** [comment]
I have learned a lot about git since I started this pull request. I think I'll rework it over Christmas.

**Pull request closed without merging**
