### PR TITLE
Metal Trapdoor.

### PR DESCRIPTION
**Pull request by sofar**
Adds a metal trapdoor. Textures were painted from scratch, and
inspired by the current Metal Door. Ownership on the trapdoor
works as expected, and so does the crafting recipe.

### CODE REVIEW

**Comment by kilbith** [comment]
:+1:

**Comment by paramat** [comment]
:+1:

**Comment by 0-afflatus** [comment]
:+1:

**Comment by JBBgameich** [comment]
Why not call it steel trapdoor? That makes more sense in the minetest_game content, but i really like the idea!

**Comment by C1ffisme** [comment]
:+1: 

And @JBBgameich 's suggestion is probably worth noting. After all, the steel door is called Steel Door.

**Comment by sofar** [comment]
Agreed, I like consistently named objects.

**Comment by sofar** [comment]
Pushed update changing all node names, references and texture names from "metal" to "steel".

**Comment by paramat** [comment]
Yes it should be 'steel'. Also i think it should be 'doors:trapdoor_steel'' to be consistent with 'door_wood' and 'door_steel'.

**Comment by sofar** [comment]
updated, addressed all comments. please merge!

**Comment by paramat** [comment]
:+1:

**Comment by Fixer-007** [comment]
If it is interacted by owner only and is non-diggable as metal door -> that will be very cool and needed feature for roof and wall protection against griefers on survival servers.

+1

**Comment by sofar** [comment]
@Fixer-007 it's exactly that - owned by placer, only diggable and can only be opened/closed by owner.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
e9a7782c883a273492c9ce2e0a7a56881218f6b3

**Pull request closed without merging**
