### PR TITLE
Fix character.b3d animation issues.

### PR DESCRIPTION
**Pull request by sofar**
Both the standing and sitting animations had misplaced curve
cusps that caused the end part of the animation to wiggle the
feet slightly back and forward.

I've fixed both animations parts and re-exported. Verified in-game
with multiplayer that everything was indeed fixed.

### CODE REVIEW

**Comment by paramat** [comment]
:+1: No more moonwalking.

**Comment by sofar** [comment]
Or moonsitting.

**Comment by 0-afflatus** [comment]
:+1:

**Comment by sofar** [comment]
This should be trivial to review - just try the model in-game walking, and sitting on a boat.

@ShadowNinja @sfan5 @Ekdohibs ? care to test?

**Comment by kilbith** [comment]
Tested. Impeccable fix.

**Comment by paramat** [comment]
I'll merge it as trivial.

**Comment by paramat** [comment]
8422f2ef52bd424cc04f43b7d32aa7b20bf30647

**Pull request closed without merging**
