### PR TITLE
Flowers: Cleaning of waterlily's placement

### PR DESCRIPTION
**Pull request by kilbith**
Here's the cleanest, quickest, non-hacky way of placing waterlilies.

Also added `sunlight_propagates = true` since shadows on the coasts and water surface were vomitive and inappropriate for such flat plant.

Cc: @paramat

### CODE REVIEW

**Comment by PilzAdam** [comment]
WTF was up with the previous code?

This seems good, although using a group instead of nodename checking would be better.

**Comment by kilbith** [comment]
> WTF was up with the previous code?

It was a monster created by paramat, lol.

About groups : checking for `liquid` or `water` would allow placing on `*_water_flowing` nodes. Should I add another group for `*_water_source` nodes or let as it is ?

**Comment by PilzAdam** [comment]
Maybe check for liquid group and then check nodedef if it's a source?

**Comment by kilbith** [comment]
Well, can directly check for `liquidtype = "source"` I guess.

**Comment by PilzAdam** [comment]
Now you can place them on lava?

**Comment by kilbith** [comment]
Right, added checking for `water` group.

**Comment by PilzAdam** [comment]
I think `minetest.registered_nodes[node]` may be nil, if pointing to an "unkown" node. In this case there needs to be an extra check. Can you test this?

**Comment by tenplus1** [comment]
on_place = function(_, _, pointed_thing)
		local pos = pointed_thing.above
		local node = minetest.get_node(pointed_thing.under).name
		local nodedef = minetest.registered_nodes[node]
		if minetest.get_item_group(node, "water") ~= 0 and nodedef and nodedef.liquidtype == "source" then
			minetest.set_node(pos, {name = "flowers:waterlily", param2 = math.random(0, 3)})
		end
	end

**Comment by kilbith** [comment]
Alright, checking added.

**Comment by PilzAdam** [comment]
:+1:

**Comment by paramat** [comment]
Will test. I had problems with my use of 'after place' which then needed lots of monsterous code to make it behave.

**Comment by sofar** [comment]
This looks great.

```
if minetest.get_item_group(node, "water") ~= 0 and nodedef and nodedef.liquidtype == "source" then
```

micro optimization, but reversing the order here makes much more sense - check for ```nodedef``` before doing ```minetest.get_item_group(```. Even ```nodedef.liquidtype``` should be checked before that.

**Comment by kilbith** [comment]
Good idea, applied.

**Comment by paramat** [comment]
Tested and good :+1: thanks for doing this.

**Comment by paramat** [comment]
47b197e4d54897170abf6ce6f283a6a24e4e1dd0

**Comment by tenplus1** [comment]
Just so you know this pull results in infinite waterlily's as the stack count never goes down when placed.

**Comment by kilbith** [comment]
https://github.com/minetest/minetest_game/pull/1021

**Pull request closed without merging**
