### PR TITLE
Beds: Fix code style issues

### PR DESCRIPTION
**Pull request by paramat**

### CODE REVIEW

**Comment by sofar** [comment]
Is there any reason not to use ```group:wool``` instead?

**Comment by kilbith** [comment]
No, please don't turn the blanket in white. Otherwise the white upper part (mat) and the blanket will be visually mixed without real distinction.

Leave it in red so that it remains attractive and cute. Add more flowers to Mapgen V7 if it's really a problem.

> Also i think it would be good to visually distinguish Minetest beds from Minecraft ones.

Is there a valid reason to or it's just for its own sake ?

**Comment by 0-afflatus** [comment]
Not white for the reasons @kilbith stated.
However, I would like to see multicoloured beds.

**Comment by sofar** [comment]
@kilbith this patch doesn't change the visual appearance or color of the bed model. just the crafting recipe.

**Comment by kilbith** [comment]
I was answering to : 

> SInce editing the textures will be a long job, i will wait for dev opinions on this PR before doing that.

**Comment by C1ffisme** [comment]
I would like multicolored beds, but only if we can have node meta set node definition.

> In all mapgens other than mgv6, roses could possibly be 1000s of nodes away.

I'm not really sure about this statement. Could someone verify this? If they were thousands of nodes away, then they obviously need to be more common.

We could also make a crafting recipe for red dye from apples.

**Comment by 0-afflatus** [comment]
> Could someone verify this?

That's a bit of an overstatement, but you generally have to explore to find roses in mgv7.

**Comment by paramat** [comment]
I realised this is not an issue, since to get wool you need cotton seeds from junglegrass, and jungles are usually more distant than roses.
I was indeed going to change the textures, and am happy to avoid that now.
Flowers can be distant yes, but only because biomes are larger and more varied than in mgv6.

I will change this PR to be a code cleanup only, it really needs it.

**Comment by paramat** [comment]
Updated to clean up code in all files.
WIll merge soon as is trivial.

**Comment by paramat** [comment]
45bc0b245ffec79d3a1656bd6dc9f4ebc498a746

**Pull request closed without merging**
