### PR TITLE
New header image

### PR DESCRIPTION
**Pull request by kilbith**
This pull includes 6 new styles of header images. Vote for the one you prefer.

both_main

In-game preview for the basic one : https://mediacru.sh/hxnE0yYP-a3e
In-game preview for the basic one (style2) : https://mediacru.sh/g8G0cZX5yr6j
In-game preview for the cubic one : https://mediacru.sh/4xB5bbwHDtkC
In-game preview for the cubic one (smaller cubes) : https://mediacru.sh/54Lmn02G2Lsn
In-game preview for the letters-land one (style 1) : https://mediacru.sh/T9bW-d9KnZDx
In-game preview for the letters-land one (style 2) : https://mediacru.sh/SX6pvCYVZqYu
In-game preview for the letters-gameland (style 1) : https://mediacru.sh/CoXjwVwGryrp
In-game preview for the letters-gameland (style 2) : https://mediacru.sh/mzkEQC1COS6l

### CODE REVIEW

**Comment by kilbith** [comment]
@ShadowNinja  : added a new header with smaller, sharper, more or less aligned cubes. See my 1st comment.

**Comment by kilbith** [comment]
@PilzAdam, asking for a defensive "why a new header ?" is not a surprise because I observe you're always conservative... The current one is lousy and disharmonious.

**Comment by kilbith** [comment]
I'm waiting for new ideas for filling the letters. But I really dislike the current texture which is not representative of the game AT ALL.

**Comment by kilbith** [comment]
Update : added a new style of letters-land (2 variants). See my 1st comment.

**Comment by kilbith** [comment]
Update : added new styles of letters-gameland (2 variants). See my 1st comment.

EDIT : added a variant for the basic one.

**Comment by kilbith** [comment]
@CasimirKaPazi: I don't understand what you're talking about. Here it concerns the _replacement_ of the header image, and you don't have to update it on every texture change at all.

**Comment by kilbith** [comment]
Current summary of the most popular headers :
- Letters-land (style 1) : 7 positive feedbacks.
- Letters-gameland (style 1) : 8 positive feedbacks.
- Basic : 3 positive feedbacks.
- Some others with 1 or 2 votes.

**Comment by kilbith** [comment]
@sfan5 favorites : http://irc.minetest.ru/minetest-dev/2014-12-06#i_4051391

So we have a massive majority of votes for letters-land & letters-gameland.

BUT...

1) Letters-land is cartoon style and might not fits always good or appropriate in the future menu(s).
2) Letters-gameland is exposed to the problem of textures changes. Although the general aspects of grass / stone / whatever-in-land will remains always approx. identical - so it's not that a problem.
3) In my mind, the basic one is the most versatile & sustainable thanks to its "neutral" aspect.

Time to take a decision @sfan5 @nore @BlockMen. 0.4.11 approaching...

**Comment by kilbith** [comment]
@sfan5 : great idea. The question now is who is willing to code that ?

**Comment by kilbith** [comment]
PR closed. Tired.

**Comment by C1ffisme** [comment]
Letters land 1, style 2. The old header does not fit minetest's theme. It is too high definition and looks more like a stone cliff face rather than blocky virtual land.

**Comment by kilbith** [comment]
I close since https://github.com/minetest/minetest_game/pull/489 will update the header. Thanks for all your votes, though.

**Comment by kilbith** [comment]
> small idea I just came up with: We choose serveral headers and the engine randomly displays one of them

https://github.com/minetest/minetest/commit/899491325938d0b1e5bf701d33d24bb4283affaa

**Pull request closed without merging**
