### PR TITLE
Add steel door/trapdoor sounds.

### PR DESCRIPTION
**Pull request by sofar**
I've found a favorable steel door sound from a parking garage
door that isn't abrupt or scary, just sounds like a nice solid
metal door. The sample had both opening and closing sounds, and
so they match nicely. Amplified and mixed several samples together
to reduce ambient noise, and get the right level compared to
wood doors. Attribution was added as well. CC-BY-3.0 sounds.

### CODE REVIEW

**Comment by sofar** [comment]
Slightly upped the volume. Nice loud *clang* when you close it.

**Comment by paramat** [comment]
Nice idea will listen later.

**Comment by paramat** [comment]
:-1: Not keen on these, open is unpleasantly squeaky with a harsh reverb, and close is a sudden slam that scared the f*** out of me. Steel doors can be nice and weighty and solid like a wooden door so the wood sound seems okay for the moment.

**Comment by sofar** [comment]
Meh, the default door sounds like a roll curtain to me :(

**Comment by sofar** [comment]
I'm dropping this PR for now. I'll leave the branch in case people are interested in it for mods.

**Comment by sofar** [comment]
#887 - new metal door sounds. Please listen and review!

**Comment by paramat** [comment]
:+1: Exactly what i had in mind, a nice solid security door sound.

**Comment by paramat** [comment]
Maybe this could be used for glass doos also, since it's a modern and non-wooden sound? Or at least until other sounds for glass doors are found. Maybe reduce the volume for use with glass doors.

**Comment by srifqi** [comment]
+1 for steel door sounds.



> Maybe this could be used for glass doos also, since it's a modern and non-wooden sound? Or at least until other sounds for glass doors are found. Maybe reduce the volume for use with glass doors.

How about higher pitch?

**Comment by sofar** [comment]
while pitching it up may work, it would just be the same sound and people would recognize it. I'd prefer looking for another sound sample, but it is an option.

**Comment by kilbith** [comment]
:-1:

The closing sound have 2 "sonorities" of closing. I'd prefer one single and prompt closing sonority.

The opening sound does not seem to be produced by a door. This is very snappy, thin and without reasonance.

**Comment by sofar** [comment]
@kilbith this is made from the recording of ... a door. Please follow the link in the README.txt.

**Comment by 0-afflatus** [comment]
Sure but Joe Meek rarely allowed drummers to use bass drums. He found shod feet better. YMMV

**Comment by paramat** [comment]
Ok no problem, glass dors are best another sound.
2 sonorities: security doors often have complex latch systems, the multiple sounds make it sound more secure.

**Comment by sofar** [comment]
Rebasing. @ekhidobs @sfan5 @ShadowNinja ?

**Comment by paramat** [comment]
@PilzAdam please can you review? sfan5 can't review with his browser, ShadowNinja is not too keen on it, nore is busy.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
Good, will merge soon.

**Comment by paramat** [comment]
cb57f70aab363f03d464d0913f19852e6670d663

**Pull request closed without merging**
