### PR TITLE
Tweaked ice texture - seamless one.

### PR DESCRIPTION
**Pull request by RealBadAngel**

### CODE REVIEW

**Comment by RealBadAngel** [comment]
https://imgrush.com/ezvxyP09xAIp.png vs https://imgrush.com/FoYpSUN9P7sV.png

**Comment by est31** [comment]
:+1:

**Comment by asl97** [comment]
-1 i prefer it with a border, maybe use glasslike_frame

**Comment by VanessaE** [comment]
:+1:

**Comment by Calinou** [comment]
:+1:

**Comment by asl97** [comment]
a little border goes a long way
screenshot_20150708_174056

**Comment by RealBadAngel** [comment]
@asl97 
do you know of course that glasslike framed is way slower?
this way you disable grouping nodes in fastfaces rows also
not quite good idea for a node being massively used in the world

**Comment by paramat** [comment]
+1.

**Comment by paramat** [comment]
I've just discovered Gambit's latest ice texture from PixelBOX, it's stunning, screenshots coming, i think we should use that one instead if Gambit agrees.

**Comment by paramat** [comment]
screenshot_20150709_023526

**Comment by est31** [comment]
wow, that's cool. Like the gambit texture even more.

**Comment by RealBadAngel** [comment]
indeed, that one is far better

**Comment by VanessaE** [comment]
Oh yes, that IS better for sure.

**Comment by kilbith** [comment]
I prefer Gambit's one for sure (his texture pack is a gold mine for tiles, btw).

@paramat No need to ask Gambit, PixelBOX is WTFPL and `minetest_game` already uses some of his textures for ages now (see credits in the [README](https://github.com/minetest/minetest_game/blob/master/mods/default/README.txt#L195-204) from `default` and other mods).

**Comment by paramat** [comment]
Cool will make a PR.

**Comment by paramat** [comment]
Here it is https://github.com/minetest/minetest_game/pull/562

**Pull request closed without merging**
