### PR TITLE
Add another glass breaking sound

### PR DESCRIPTION
**Pull request by veikk0**

### CODE REVIEW

**Comment by kilbith** [comment]
3 sounds are not enough for you ?

**Comment by Fixer-007** [comment]
BTW, did you noticed that default glass breaking sounds are somewhat loud? Can be painful in headphones.

**Comment by paramat** [comment]
Sound is fine but i thnk 3 is enough, with most sounds we don't go beyond 3 versions.

**Comment by veikk0** [comment]
I've always thought that more sound variation would be better and that it would be nice to have more variants. I looked at the [dev.minetest wiki](http://dev.minetest.net/TODO#Sounds) and 4 was the suggested number of sounds so I thought it'd be a welcome addition.

@Fixer-007 
Now that you mention it some of the glass sounds are a bit loud. It's not really that noticable unless you're breaking a lot of glass. But the sounds could use a little tweaking.

**Comment by paramat** [comment]
I know this is weird, but i'm uncomfortable with adding a 4th sound for one thing when many others are still in need of a 3rd. For now i would prefer we don't add 4th sounds and focus on the others that only have 2.
:-1:

**Comment by MarkuBu** [comment]
Befor adding new glass sound better add sounds for ice. It still uses the glass sound. That's weired

**Comment by sofar** [comment]
If the existing 3 sounds are really similar, then I'd remove one of them and add a new sound. This isn't an exact science, it comes down to taste. Perhaps this new sound is too different than the old sounds, etc..

disclaimer: I didn't listen to the new and old sounds to compare.

**Comment by paramat** [comment]
Our break glass 1 sound is not too good, and this submission compliments 2 and 3 nicely, i suggest replacing sound 1 with this submission?

**Comment by paramat** [comment]
Closing due to no reply for a month.

**Pull request closed without merging**
