### PR TITLE
Wooden Sign: Add group oddly_breakable_by_hand

### LINKED ISSUE #942: Wooden sign can only be digged by axes
Picaxes, swords, shovels and hands are not able to dig wooden signs.

**Edit: In stable 0.4.13 it was breakable by hands, wooden tools/swords (and stronger), except of hoes**

### PR DESCRIPTION
**Pull request by kilbith**
Fixes #942 

Did I forget something else ?

Cc: @PilzAdam @paramat

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by Fixer-007** [comment]
:+1:

**Comment by PilzAdam** [comment]
> PilzAdam approves in the issue, so can be merged.

Yes, he does.

**Comment by kilbith** [comment]
https://github.com/minetest/minetest_game/commit/c3d2bc383b172d87ca920522dab6b5de1e82a14d

**Pull request closed without merging**
