### PR TITLE
Remove deprecated ore generation code

### PR DESCRIPTION
**Pull request by Calinou**
This code has been deprecated for several years now. I believe no mods are using it currently, if so, they should switch to the faster C++ ore generation.

### CODE REVIEW

**Comment by rubenwardy** [comment]
:+1:

**Comment by C1ffisme** [comment]
:+1: 

If mods are using it, they can copy the function from an older version of minetest. We are removing support for some mods for 0.5.0

**Comment by rubenwardy** [comment]
It's been deprecated for 2.5 years, it wouldn't need to be a 0.5 release IMO.

**Comment by C1ffisme** [comment]
That's true. :P .

**Comment by rubenwardy** [comment]
Older versions of Homedecor use it to test for versions, but is now removed: https://github.com/bas080/simple/blob/577887abfcc4d9fc35a5dae2dd6cb2451276e5ab/mods/homedecor/door_nodes.lua#L19

**Comment by paramat** [comment]
Agreed, i wanted to remove this myself when i last worked on this file.

**Comment by paramat** [comment]
Please can you re-add the newline at end of file? then i'll probably push this.

**Comment by PilzAdam** [comment]
What's the benefit of removing it? There is no additional effort needed to maintain it, is there?

**Comment by kilbith** [comment]
@PilzAdam What's the benefit of emptying your garage of unnecessary things ? Stop conserve for the sake of conserve...

**Comment by Calinou** [comment]
> Please can you re-add the newline at end of file? then i'll probably push this.

https://github.com/Calinou/minetest_game/blob/35c2c8f9428b63344a1887397f9a3d8f254b8f98/mods/default/mapgen.lua

If you open the file in a text editor, there is already a newline at end of file. I set my editors to always add a newline when saving when there isn't.

**Comment by HybridDog** [comment]
>If mods are using it, they can copy the function from an older version of minetest.

maybe you could let default.generate_ore call minetest.register_ore

**Comment by rubenwardy** [comment]
AFAIK, register-ore is called only on start up and generate ore is called
from on_mapgen. Unless it's misnamed.

**Comment by paramat** [comment]
Thanks Calinou.

**Comment by paramat** [comment]
6919d43d025a26b9ad795283273aa4e5380a78ec
The newline didn't appear but nevermind i'll add it next time i edit the file, which will be soon.

**Comment by rubenwardy** [comment]
@paramat: there is a newline there, GH just doesn't show it.

**Pull request closed without merging**
