### PR TITLE
New header image 'Minetest Game'

### PR DESCRIPTION
**Pull request by paramat**
minetest main menu _006

See https://github.com/minetest/minetest_game/issues/480#issuecomment-145301062 onwards for previous discussion.

This is with default GUI scaling and a 1280x720 window.
Header image is 192x16px and is upscaled automatically to what you see here.
Each letter is 16x16 'pixels', the 'I' and the gap are 8 'pixels' wide.
It uses the default:stone texture with a higher contrast version of stone brick shading.
There's more freedom to adjust GUI scaling without overlapping the header.

ShadowNinja commented on 19 Apr https://github.com/minetest/minetest_game/pull/489#issuecomment-94215472

> A photorealistic title belongs in something like HDX. The title should be much simpler, and probably very low res.

I agree and was inspired to make a low resolution image using Minetest Game style 16x16 textures arranged in a line of nodes (1 vertical slab for the 'I'), similar to the current header in using blocky letters in a stone texture.

A possible improvement i am considering is making the stone texture a lighter grey and using stronger bevel shading, for the header to appear brighter and smoother. However i'm fairly happy with it as it is.

### CODE REVIEW

**Comment by sfan5** [comment]
:+1:

**Comment by PilzAdam** [comment]
https://github.com/minetest/minetest_game/issues/480#issuecomment-145329456

I'd first like to see if someone has an idea for a different base than the current stone. If not, then :+1:

**Comment by kilbith** [comment]
> I'd first like to see if someone has an idea for a different base than the current stone

Perhaps dirt with grass ?

**Comment by paramat** [comment]
I will work on tuning the brightness and contrast for a lighter grey, to provide some alternatives.

I considered what other texture could be used for the letters, stone is good because it is the fundamental base terrain node, the most common and primary node in a world. It is also a classic old texture that is not likely to change. Because it is grey it is colour-neutral against the blue sky.
I'm not keen on dirt and grass as i find the textures a little ugly, it's also an overused combination in MT and MC forums etc.

**Comment by ShadowNinja** [comment]
:+1:

**Comment by paramat** [comment]
minetest main menu _007

I made the shading more intense, appears smoother and more defined, not as subdued by the bright backgound sky. I hope this is still okay, i think it is an improvement.

**Comment by nerzhul** [comment]
Too many stone, can we have more than stone on the image ? it's very freezy image

**Comment by PilzAdam** [comment]
@paramat this is indeed an improvement. I'd say merge this for now, and future designers may find a replacement for the stone texture.

**Comment by est31** [comment]
Logo contest?

**Comment by paramat** [comment]
70e892408261b5a4711f52b62048f8cc061655a4

**Pull request closed without merging**
