### PR TITLE
Default: New sandstone brick texture

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150524_023632

^ The new submitted texture.

After i enabled sandstone dungeons i noticed the sandstone brick texture has some green and white colouration. Experimenting with Gimp i tried using the pencil tool in 'value' mode to lighten and darken the sandstone texture without affecting colour. The image was converted to indexed form before exporting as .png to match the original sandstone texture and reduce it's filesize.

The darkest pixels in the current texture are a mortar. My submission has no mortar showing (it can still be consideed to be there as a thin layer) for two reasons:

First, mortar gives bricks a cheap, rough and commonplace appearence which may be suitable for cobble and red brick, but sandstone brick will be used for pyramids, temples and tombs where precisely cut close fitting sandstone blocks look much more suitable (for this reason i feel desert stone brick and obsidian brick should also not have mortar due to their use in exotic, magickal or sinister constructions).

Second, a brick node on it's own, or the end of a 1 node thick wall, currently has unequally sized lower bricks of 8 and 7 pixels, this looks rough and ugly.

Comparison of submitted and current:

screenshot_20150524_022630

### CODE REVIEW

**Comment by kilbith** [comment]
You have somewhat broken the bricks relief and their separation is inconsistent.

2015-05-23-103114_1280x800_scrot

The 2 red dots positions indicate : 
- The dark vertical separations are incomplete (lack one pixel for each of them).
- The brick borders are too clear, and inappropriately placed (i.e. the middle one is all along the texture without separation (respectively for each brick)).

Also : there's no darker contrast at the opposite sides for balancing the clear borders and giving it a "relief". See here the following example pointed by the green dots : 

dsfc

Conclusion : I'm against your texture currently :-1:

**Comment by paramat** [comment]
Yes that's all intentional, i am removing the mortar and making the bricks 16x8 pixels and in direct contact. The dark pixels are the relief of the lowest part of the bricks. The shading is continuous horizontally because i decided it should override the vertical shading. I do have another version of this texture with corner-faceting:

screenshot_20150518_055018

I will be adding more contrast to the shading.

**Comment by C1ffisme** [comment]
They look fine to me. They actually look slightly better than the first texture, although with every tiny texture change, I never quite see it.

**Comment by paramat** [comment]
Updated texture with more contrast and corner bevels.

**Comment by kilbith** [comment]
@paramat This is something missing (shadow) for the relief effect : 

7a8b7f98-01d1-11e5-922f-8ce518005f92

I still prefer the current texture.

**Comment by HybridDog** [comment]
you could also use texture modifiers instead of a sandstone brick texture

**Comment by paramat** [comment]
kilbith see above:

> My texture has no mortar showing, so the missing darker contrast you mention is actually there at the base of the 16x8 bricks.

**Comment by kilbith** [comment]
It's not the mortar, it's the smooth shadow given by the "relief" of the brick. Your texture is too flat.

**Comment by paramat** [comment]
My bricks have deeply bevelled edges and corners and more relief than the current texture. The face of the brick is flat so would not have smooth shading. What you point out is actually the bevel-shadow of the current texture, the bricks do not have curved faces.

Watching a Minecraft video i noticed their sandstone block texture has the same sickly green mortar. Very ugly and unsuitable for the exotic tombs they use it for. No pharoah would accept a tomb or pyramid made with curved bricks and mortar =)

**Comment by sfan5** [comment]
:+1:

**Comment by VanessaE** [comment]
Already said this in IRC but it bears repeating here:  the new brick texture lacks contrast along the relief, probably because they lack the mortar lines.

**Comment by tenplus1** [comment]
The new texture looks good to me and your explanation for close-fitting stones hence lack of mortar is a good one...

**Comment by Zeno-** [comment]
As a pharaoh myself I am pretty ambivalent.

**Comment by HybridDog** [comment]
How did you make the sandstone floors so sleek?

**Comment by paramat** [comment]
Lol Zeno.
VanessaE you were quite right about the first submission lacking contrast, this one has a little more although not as much as the original. Because sandstone is such a light material even the shadowed areas would not be particularly dark.

**Comment by paramat** [comment]
I will add in new obsidian brick and desert stone brick textures to this PR, taking a similar approach, they really need improving.

**Comment by kilbith** [comment]
> taking a similar approach

I can say by advance that we ought rather have different patterns for each bricks for being original.

**Comment by paramat** [comment]
Think i'll keep this PR down to 2 textures, as only obsidian brick seems suited to a similar approach to sandstone. Desert stone brick is probably best left having mortar, like stone brick, it has some discoloured shaded pixels which would look good redone with pencil in value mode, something for another PR.

**Comment by paramat** [comment]
Sfan5 seems to like it, so if another MTGame dev approves i can push this for you if you like, let me know.

**Comment by Novatux** [comment]
Looks good!

**Comment by paramat** [comment]
03b51e8c8ff6ef3186732ad877cb64718eaaa47f

**Pull request closed without merging**
