### PR TITLE
Add Crafting for Dirt with Grass

### PR DESCRIPTION
**Pull request by C1ffisme**
This makes landscaping a bit easier.

You can combine one grass plant with one dirt to get grass.

**Note:** My git is quite primitive, and so I made this in the Github editor. If something is messed up, just tell me so I can shut this down and try to do it better.

### CODE REVIEW

**Comment by C1ffisme** [comment]
I might want to make the recipe shapeless, just as a thought.

**Comment by PilzAdam** [comment]
:-1:, grass will eventually grow. You can't speed up nature.

**Comment by kilbith** [comment]
:-1: Bullshit.

**Comment by C1ffisme** [comment]
@PilzAdam @kilbith Mostly I was told sofar might consider this.

To be fair, I'm not sure if I like this either, but I might as well put this here for discussion.

(@kilbith Not necessary... Seriously.)

**Comment by sofar** [comment]
@kilbith really, that reaction is unnecessary. This isn't the type of PR where banalities are needed.

@pilzadam grass will eventually not grow after #999, moreover, dirt with dry grass doesn't ever grow. You also can't plant grass in caves or under a canopy, since it requires full light.

So, there is a completely normal demand for these recipes, or some way to obtain these two blocks.

**Comment by sofar** [comment]
@C1ffisme please make the recipes shapeless, yes.

**Comment by PilzAdam** [comment]
Okay, I see the problem you want to solve. This is still a bad way to solve it, though. Maybe turn `default:dirt` into `default:dirt_with_grass` if `default:grass_*` is placed on it? That way we still have the "growing" outside of the crafting grid, which makes much more sense.

**Comment by RHRhino** [comment]
I see no need for being able to craft drit with grass, because it is already converted by default. The only thing we lack right now is dirt with dry grass. For me the recipe `dirt+dry grass (plant)` sounds okay as well as `dirt + placed dry grass plant on top` of it. I think it would also be okay if you would be able to convert dirt to different dirt with grass nodes in the crafting table for landscaping without crafting it with the grass plants.

**Comment by Ferk** [comment]
@RHRhino  that's covered by https://github.com/minetest/minetest_game/pull/999

In there there's also a conversation about making grass play more fair with dry grass (and other dirt growths) by making it require a neighbor dirt_with_grass to grow, instead of always growing whenever light >13 ... which is I think the motivation for this PR.

But there should be a discussion about that instead. It makes little sense to add this if the limitation in grass growth is not gonna be added, imho. Because then you can just expose the grass to >13 light to grow it.

**Comment by sofar** [comment]
@pilzadam placing grass/dry grass on dirt sounds like an excellent method to solve the problem. I think we want the grass/dry grass to be consumed to prevent repeating it over and over again.

**Comment by sofar** [comment]
@C1ffisme I think we can just close this thread and continue the discussion in #999

**Comment by paramat** [comment]
Agreed this can be combined into #999 inside that ABM there could be checks for long grass or long dry grass above the dirt node.

**Comment by C1ffisme** [comment]
Sorry for my absence, I decided to take a day off Github, because of @kilbith 's reaction. It made me feel bad.

Come on, man. Realize that your words can hurt people. Please.

**Comment by Xanthin** [comment]
I guess you misinterpreted kilbith's comment. It wasn't an unnecessary rude feedback adressed to you rather a hint to PilzAdam's statement.

> You can't speed up nature.
 
> Bullshit.

^ This indeed can and does speed up nature (he also could have chosen guano). But unfortunately it would require a mob to drop bullshit, to get the fertiliser. So a probably better idea would have been:

> Compost.

**Comment by C1ffisme** [comment]
@Xanthin Uh... What??? Am I supposed to laugh, or take this seriously?

Compost is... a (possibly good) idea... but kilbith was *definitely* not talking about that as a feature.

If you will look at his other posts, he forms... grudges.

If he meant to say compost, he should have said compost. That would have been far less offensive. Far less.

**Comment by Xanthin** [comment]
Of course that was a humorously turn of the perspective and a small attempt to form bullshit into, not gold, but maybe tin.

**Comment by kilbith** [comment]
When a small puppy relieves oneself at home, I put his nose in his own poop so that he no longer redo that the next time.

**Comment by C1ffisme** [comment]
@kilbith Great. Guess what? None of us are puppies. Nor are we... anywhere... near that level of intelligence. Let us act like civilized human beings.

And who gave you the authority to discipline? Being a core-dev can give you abilities, like merging pull requests and having respect, but not dictating who is being stupid.

I will admit, this pull request was pretty stupid, and I should have used a shapeless recipe, and had a better discussion on it. But Bull@#!$ is not discussion.

**Comment by rubenwardy** [comment]
> And who gave you the authority to discipline? Being a core-dev can give you abilities, like merging pull requests and having respect, but not dictating who is being stupid.

kilbith is not a core-dev and never has been.

**Comment by C1ffisme** [comment]
@rubenwardy Hmm... I thought he was for a while. I guess his and sfan5's avatars looked similarish (They were both pink) for a while.

**Comment by 0-afflatus** [comment]
@C1ffisme you can safely ignore kilbith's graceless delusions of self-importance just like everyone else does.

**Comment by kilbith** [comment]
> you can safely ignore kilbith's graceless delusions of self-importance just like everyone else does.

Is this a joke or real infamy ? I don't think you know very well the contributor and individual as I am, nor my historical and level of interaction with the maintainers.

And who are you even to frequently offend me like that ? Respect is the currency we use for paying the contributors, keep offending me like that and I'll certainly ignore you at best or even stop contributing, if it's what you want.

**Comment by 0-afflatus** [comment]
@kilbith my comment is considerably less offensive than those you make on a regular basis. This is precisely about respect. It offends me deeply that you use crude and emotive language to put down people you don't respect. It is irrelevant who I am, I am simply a person who reads this issue tracker. 

You are an excellent coder and I have learned a lot from studying your work and reading your more constructive criticisms, however I really wish you would stop making ad hominem attacks and stick to factual criticisms of the issues concerned. I don't expect flowers or false manners from anyone on here. On this issue all you needed to do was thumb it down. If you had time and inclination a constructive criticism of the PR would be appropriate, if not you are simply adding to the noise. We are not doing dog training here - C1ffisme is a human being with feelings, albeit frequently noisy and inappropriate. If you find it hard to empathise, then I would appreciate it if you would adopt a stricter ruleset about how you respond. If you responded with greater grace and dignity towards those less skilled than yourself you would certainly earn my respect.

**Comment by kilbith** [comment]
C1ffisme is guilty from durably making noise on the whole tracker and has no value. The strong language was only directed to the PR at first. If people take that personally, that's not my problem and there's no reason to improvise an indictment against a villain.

You have been throwing me some spikes of offense since months already - so far I did not react to this, but enough is enough. This is misplaced when you're not more or less equally ranked to the person you attack. Don't see arrogance here, it's just common sense and tacit social conventions that apply everywhere.

And I'm ceasing my unproductive talk right now. Consider my warnings above.

**Comment by Zeno-** [comment]
I think the mud flinging has gone too far. Locking.

**Pull request closed without merging**
