### PR TITLE
Add steel sign + Update wooden sign texture

### PR DESCRIPTION
**Pull request by kilbith**
As requested in https://github.com/minetest/minetest_game/issues/883
- Crafting yields changed from 1 to 3.
- Wooden sign texture updated to simpler and more wood-ish looking (texture by Gambit).

capture d ecran de 2016-03-06 11-45-26

capture d ecran de 2016-03-07 11-14-18

Cc: @PilzAdam @paramat

### CODE REVIEW

**Comment by PilzAdam** [comment]
Using a loop here is not needed. Maybe create a local table `generic_sign`, register both nodes with it and use `override_item` to change the fields that differ between them?

**Comment by kaeza** [comment]
:+1: for the idea, but the code definitely needs work.

**Comment by kaeza** [comment]
Sorry for posting multiple times. Was going to comment on individual lines, but would be better to do it here.

I agree with @PilzAdam. A better approach, IMHO, is to define a helper function `register_sign` taking only the differences (e.g. groups, description) and filling in the rest. Maybe even something similar to the (relatively) recent `doors.register` function.

**Comment by C1ffisme** [comment]
:+1: I really like the new texture.

**Comment by paramat** [comment]
I like the textures and support the addition of a steel sign.
I think the wooden one should have some darkened pixels in the same pattern as the steel one, to represent writing.

**Comment by kilbith** [comment]
@PilzAdam Updated.

I'll handle the wooden texture tomorrow.

**Comment by kilbith** [comment]
@paramat Wooden texture updated. See 1st comment.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.ru/minetest-dev/2016-03-07#i_4551956

**Comment by paramat** [comment]
aa676ab87863a8d42050d56355db1b25e07ce4bd

**Pull request closed without merging**
