### PR TITLE
Default: Add jungletree_branch node, use in tree generation

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160307_231308

^ Mgv7 mapgen trees (sapling grown trees are checked too)

screenshot_20160307_231450

^ Mgv6 sapling grown trees

Will need to update mgv6 mapgen trees in engine.
No longer is the interior of default:jungletree exposed when used for roots or branches.
The new node has the exterior texture on all 6 faces, and drops the normal default:jungletree.
It is randomly rotated for mgv6 sapling-grown trees. In other mapgens the roots are orientated towards the trunk and the branches have balanced variation.
It's called "_branch" and not "_root" because later i will probably add branch nodes for other trees.
The node will be useful in creative for players to build trees.

Let me know if you'd rather mgv6 trees stayed unchanged, setting rotation in the voxelmanip slows mgv6 tree-from-sapling generation down a little.

### CODE REVIEW

**Comment by C1ffisme** [comment]
Eh... I'm neutral on this. What about adding a "allsides" rotation value for facedir?

**Comment by paramat** [comment]
Updated with rotation variation.

**Comment by MT-Modder** [comment]
:+1: I like it, especially with the new top texture. It fits better.

**Comment by C1ffisme** [comment]
@paramat The rotation I am talking about is making facedir have an "allsides" value, then applying it to the original tree block.

**Comment by paramat** [comment]
That's not a good idea.

**Comment by C1ffisme** [comment]
@paramat Eh... I was taking it from minecraft. It's not my most creative idea.

**Comment by 0-afflatus** [comment]
I'm :+1: on ranch nodes - this could help solve a few problems.

**Comment by Thomas--S** [comment]
:+1:
But I suggest to add branch nodes for all kinds of trees. They could be e.g. very helpful for building.

**Comment by paramat** [comment]
Yes branches for other trees might come later in other commits.

**Comment by paramat** [comment]
One approval, my own.

**Comment by Thomas--S** [comment]
@paramat Thanks for the information.

**Comment by PilzAdam** [comment]
I'm not sure if an extra node is needed. Wouldn't it be enough to place the nodes with a sideways rotation?

**Comment by kilbith** [comment]
Or just turn the current junglewood all-faces identical. That would make more sense.

**Comment by C1ffisme** [comment]
@paramat Approving your own pull request isn't the best idea. That would be like letting a presidential candidate veto on his opponent's victory in office.

**Comment by paramat** [comment]
PilzAdam, any rotation would leave inside showing.
If jungletree had all 6 faces with exterior textures it would look weird when removing nodes.

C1ffisme this is how the new labels are used, a dev's own approval does count for a PR so should be shown in labels, as long as that dev is happy with the PR and it is not WIP.

**Comment by C1ffisme** [comment]
@paramat Maybe if this is from a code-wise perspective. However, from a gameplay-wise perspective, there is easily 1 core dev who does not know how to develop games, and just wants to see any feature go into minetest. (I'm not saying there is, but I'm sure it can happen.)

Thus, it gets two approvals. One from this core dev, and one from the pull request maker. (Because it wouldn't make sense to make a pull request for something even *you* don't want.)

**Comment by PilzAdam** [comment]
@paramat 
>any rotation would leave inside showing

yes, I know that. I was asking it this would be good enough.

**Comment by paramat** [comment]
Ah i see. I think the orientation doesn't make much difference to considering whether the inside shows or not.

I think part of this PR is because i'm a little unsure about my jungletree top texture, because i made it octagonal it looks round from a distance, which looks out of place, this may be making me want to hide it. I think i need to work on the texture while we consider this.

**Comment by paramat** [comment]
I'm redoing the jungletree top texture, and don't consider this essential for release, removing milestone.

**Pull request closed without merging**
