### PR TITLE
Creative: move player datas in separate table

### LINKED ISSUE #812: Creative: A vulnerability could remove table element by player name
Error occurred when I used "update" to player name.
(replaced creative_inventory.update)

The cause: https://github.com/minetest/minetest_game/blob/master/mods/creative/init.lua#L8

### PR DESCRIPTION
**Pull request by kilbith**
Fixes #812. If the nick "update" is used, variables are not declared at initialization, since it was trying to call a function.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Would a better fix be to store the player data in creative_inventory.players?

**Comment by kilbith** [comment]
Nah, this fix is simpler.

**Comment by rubenwardy** [comment]
Simpler doesn't mean the best fix. I guess it isn't so bad if the maximum player name length is shorter.

**Comment by paramat** [comment]
:+1: also makes function names more consistent and descriptive.

**Comment by davisonio** [comment]
Also, we should rename all the functions to `creative.` from `creative_inventory.` (with legacy code). This will mean it follows the naming conventions. (The mod used to be called creative_inventory)

**Comment by ShadowNinja** [comment]
Player data definitely shouldn't be intermingled with the API.  Put them in their own table instead of reusing the API table.

**Comment by paramat** [comment]
ShadowNinja commented on IRC
> First was done wrong in the first place leading to the bug, and the design should be fixed instead of hacking around it by making the function name longer than the default max player name length

**Comment by kilbith** [comment]
- Player datas moved in separate table.
- Function prefixes renamed to `creative` to follow naming conventions.

Everyone's happy ?

**Comment by Ekdohibs** [comment]
:+1:

**Comment by davisonio** [comment]
:+1:

**Comment by kaeza** [comment]
:+1:

**Comment by paramat** [comment]
:+1: Will merge soon.

**Comment by paramat** [comment]
0ea23a50d3788e14bb99e5c215f70cb85a73c98f

**Pull request closed without merging**
