### PR TITLE
Make leaves climbable

### PR DESCRIPTION
**Pull request by Wayward1**
Adds "walkable = false," and  "climbable = true," to the leaves in nodes.lua

### CODE REVIEW

**Comment by C1ffisme** [comment]
I don't know about this...

**Comment by PilzAdam** [comment]
I like this. It may break existing structures though, so I am against merging it.

**Comment by kilbith** [comment]
Climbable makes sense but I wonder about non-walkable : those leaves are sometimes used as a hedge around homes for privacy matter.

@C1ffisme : not constructive at all.

**Comment by Wayward1** [comment]
Hmm... Upon further consideration, it may be the same problem as #382- More realistic, but as @PilzAdam said, it would break existing structures.

**Comment by C1ffisme** [comment]
Actually, I used to play on 0GB's server, somebody had a floor out of leaves, so maybe there is another solution to the climbing trees problem?

**Comment by Wayward1** [comment]
Maybe it could be made toggleable in the minetest.conf or game.conf

**Comment by CasimirKaPazi** [comment]
The main problem with this is when fancy leaves are turned off. You would see just a black screen when climbing.

**Comment by C1ffisme** [comment]
@CasimirKaPazi Yeah I remember seeing that when PilzAdam did this in his subgame.

**Comment by Novatux** [comment]
Closing, since it won't be added

**Pull request closed without merging**
