### PR TITLE
Make books writable

### PR DESCRIPTION
**Pull request by ShadowNinja**
See #406.

### CODE REVIEW

**Comment by kilbith** [comment]
:heart:  It just miss ..default.gui_bg_img..

**Comment by ShadowNinja** [comment]
@kilbith I don't notice any difference with or without any of the `gui` things.  Maybe the colors were made the Minetest default and should be removed?  It seems like `bg_img` is sized for a different formspec anyway.

**Comment by MT-Modder** [comment]
@ShadowNinja I notice a difference.
Without default.gui_bg_img - 
screenshot_2255050
With default.gui_bg_img - 
screenshot_2310117

**Comment by PilzAdam** [comment]
I don't like that books are `stack_max = 1` with this. It makes crafting a lot of bookshelfs a PITA.

**Comment by MT-Modder** [comment]
@PilzAdam Good point. I'm pretty sure without ```stack_max = 1``` the whole stack has the same title and contents. I wonder if there is an easy solution to this? Maybe one book can be separated from the stack, if there is room in the inventory, when on_place is called. This single book would then have the metadata but the rest of the stack is untouched.

**Comment by tenplus1** [comment]
I've tweaked the code a little so that text is word-wrapped when reading the book also (players forgetting to hit enter after each line), it looks a little better now:

```

--= Book (use to read or write to)

minetest.register_craftitem(":default:book", {
	description = "Book",
	inventory_image = "default_book.png",
	groups = {book=1},
	stack_max = 1,
	on_use = function(itemstack, user, pointed_thing)
		local player_name = user:get_player_name()
		local data = minetest.deserialize(itemstack:get_metadata())
		local title, text, owner = "", "", player_name
		if data then
			title, text, owner = data.title, data.text, data.owner
		end
		local formspec
		if owner == player_name then
			formspec = "size[8,8]"..default.gui_bg.. -- default.gui_bg_img..
				"field[0.5,1;7.5,0;title;Title:;"..
					minetest.formspec_escape(title).."]"..
				"textarea[0.5,1.5;7.5,7;text;Contents:;"..
					minetest.formspec_escape(text).."]"..
				"button_exit[2.5,7.5;3,1;save;Save]"
			minetest.show_formspec(user:get_player_name(), "default:book", formspec)
		else
			formspec = "size[8,8]"..default.gui_bg.. -- default.gui_bg_img..
				"button_exit[7,0.25;1,0.5;close;x]"..
				"label[0.5,0;"..minetest.formspec_escape(title).."]"..
				"label[0.5,0.5;by "..owner.."]"..
				"textarea[0.5,1.5;7.5,7;text;;"..
					minetest.formspec_escape(text).."]"
			minetest.show_formspec(user:get_player_name(), "default:lockedbook", formspec)
		end
	end,
})

minetest.register_on_player_receive_fields(function(player, form_name, fields)
	if form_name ~= "default:book" or not fields.save then
		return
	end
	local stack = player:get_wielded_item()
	if minetest.get_item_group(stack:get_name(), "book") == 0 then
		return
	end
	local data = minetest.deserialize(stack:get_metadata())
	if not data then data = {} end
	data.title, data.text, data.owner =
		fields.title, fields.text, player:get_player_name()
	stack:set_metadata(minetest.serialize(data))
	player:set_wielded_item(stack)
end)

**Comment by kilbith** [comment]
@tenplus1 : instead of paste the whole code, tell us what exactly you have changed at which line(s). That'd be easier to find the change(s).

**Comment by C1ffisme** [comment]
@ShadowNinja  Rather than default.gui_bg_img, why not make some (slightly) nicer looking background images like here: #417.

**Comment by est31** [comment]
:+1:

**Comment by BlockMen** [comment]
I agree with @PilzAdam.
I think a better solution would be a new item, like written_book. Then you could still stack blank books as ususal and could handle the written books seperatly

**Comment by est31** [comment]
I don't see any point in the normal ""blank" books -- what can you do with them?
Books are for writing into them, not stacking them. We are on the road to 5.0, so stuff may change.

**Comment by PilzAdam** [comment]
@est31 The main usage of books is to craft bookshelfs. If you want to craft a larger amount of bookshelfs then you need very large amount of books, so they need to be stackable.

**Comment by est31** [comment]
ah ok, then I support @BlockMen's suggestion.

**Comment by HybridDog** [comment]
>We are on the road to 5.0, so stuff may change.

you mean 0.5.0, don't you?

**Comment by tenplus1** [comment]
Stacking writable books removed any text placed inside them or copies that text across to all of the other books...  Bookshelves can easily be expanded with another row to hold plenty more, or better yet, more books... more bookshelves :)

**Comment by MT-Modder** [comment]
I don't think this should be merged without adding ```default.gui_bg_img```.

**Comment by C1ffisme** [comment]
Bump!

Why is this controversial? This pull adds a reason to have bookshelve inventories kept.

I do see how bookshelves will be slow to craft. I think that there is a solution. Instead of the book item being writable, there should be a new item called the "Book and Dye" which is crafted, well, you can guess, and that would be written in. Optionally, a non_creative_inventory item called a "Finished Book" could be made when doing some action with the "Book and Dye". The finished book would not be edittable.

I basically just took minecraft's method of writing books. Ah well, better to add similar features than leave newbies confused at a featureless or different method game.

**Comment by Novatux** [comment]
@ShadowNinja: could code @BlockMen 's suggestion please?

**Comment by ShadowNinja** [comment]
@Novatux: Done.

I can now see the difference without `gui_background`, but I kind of like it without the background.

**Comment by Megaf** [comment]
:+1:

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/64fa8e6be5bae28beee3b3361e927be1d6b6c8d4

**Comment by C1ffisme** [comment]
YAAAAAAAAAAAAAAAAAAAY!!!!!

**Pull request closed without merging**
