### PR TITLE
changed the formspec method

### PR DESCRIPTION
**Pull request by pinkysnowman**
switched to table.concat() for faster loading

### CODE REVIEW

**Comment by kaeza** [comment]
Conflicts with #736, and is not needed for an operation that is not executed very often.

**Comment by asl97** [comment]
table.concat is slower than joining a bunch of string **without needing to store them in a variable***

unlike the sethome, the amount of args doesn't grow ether, it will always be the same amount of args

there no reason for this, this is slower than the current code.

**Comment by pinkysnowman** [comment]
I was under the impression ".."  is slower

**Comment by kilbith** [comment]
:-1: `..` is already a concatenation meant for plain strings, you're basically using needlessly more ressources with `table.concat` (which is useful to use when your values are necessarily in an array and that is likely to be dynamically redefined).

The best way for optimizing this is to avoid the concatenation at all, i.e. make a long, continuous string (but you lost the readability).

Also rather bad-style deontologically to open a PR conflicting short after another.

**Comment by pinkysnowman** [comment]
Fuck you cock knob,  i  don't need to hear your shit.  I  have my issues
and coding helps me fucking cope,  maybe next time ill come cut your arm
leg and wrist instead of my own!  Or cut off that pitiful thing you call a
dick.

**Comment by pinkysnowman** [comment]
And you guys wonder why noone gives a fuck about deving this engine

**Comment by asl97** [comment]
@pinkysnowman now that is just rude, what kilbith said is valid

@kilbith
* if 'newline' doesn't effect formspec, `[[]]` could be use instead of long continuous string.
* pinkysnowman might not have known about that PR

**Comment by est31** [comment]
I've removed a particularly rude comment.

**Comment by 0-afflatus** [comment]
I have to say I find use of terms like 'deontologically' somewhat egregious.

**Pull request closed without merging**
