### PR TITLE
Remove spores from mushrooms.

### PR DESCRIPTION
**Pull request by sofar**
These have almost no value gameplay wise. Mushrooms spread
by their very nature into appropriate soil nearby, and
harvesting spores is something only scientists do. Actual
mushroom farmers leave a few mushrooms and put on more
manure, and keep the light off.

Modify the growth ABM to test for light levels and attempt
to plant a similar mushroom nearby (+/- 2 x,z, +/- y). Light
at both source and destination needs to be low enough. I've
tuned it to be 3-4 spaces from a torch.

Mushrooms will die in full sunlight, but they can survive under
trees and may grow out at night anywhere.

Removed obsolete textures.

### CODE REVIEW

**Comment by kilbith** [comment]
:+1: Those are pointless.

**Comment by kilbith** [comment]
By the way, you must set aliases.

**Comment by sofar** [comment]
Agreed, I just haven't figured out whether to alias it to air or a new mushroom yet.

**Comment by sofar** [comment]
Decided on aliasing them to "air". I also needed to alias the "fertile" versions to normal ones as well.

**Comment by C1ffisme** [comment]
I would alias them to mushrooms, in case someone has a mushroom farm, or mushrooms in an old world have already been collected for 1000 meters.

**Comment by sofar** [comment]
hmmmm, I need to see what actually happens in the game before I make more changes first.

**Comment by sofar** [comment]
Alright, I agree, after doing a server upgrade across old minetest_game and a new minetest_game with this patch. Both Spores and mushrooms are all converted to mushrooms, which will not result in weird nodes in people's inventory (if they had spores). People may see mushrooms hanging on the side of blocks, though, but that's not as bad as unknown inventory items.

**Comment by C1ffisme** [comment]
> People may see mushrooms hanging on the side of blocks, though,

I actually want to see that happen... I didn't know plantlike nodes could be on walls...

**Comment by sofar** [comment]
On December 15, 2015 5:57:36 PM PST, C1ffisme <notifications@github.com> wrote:
>> People may see mushrooms hanging on the side of blocks, though,
>
>I actually want to see that happen... I didn't know plantlike nodes
>could be on walls...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/minetest/minetest_game/pull/745#issuecomment-164962198

Well spores can be wall mounted, so aliasing them makes plantlike mushrooms appear in the same spot. They are normally oriented, but may be off the floor :)

I don't consider it a big deal, its likely quite rare anyway that that would happen.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paramat** [comment]
:+1: When that issue is fixed. I used to like the spores idea but have changed my mind.

**Comment by sofar** [comment]
@paramat, agreed, we definitely need to preserve mapgen mushrooms. Fixed.

**Comment by paramat** [comment]
See line note.

**Comment by kilbith** [comment]
> Might also be slightly faster code than '>= 15'

Ridiculous. It has no effect.

**Comment by paramat** [comment]
Oops indeed '== 15', obviously i know that, it was just a mistake.
It's probable that '>=' is no slower than '==', not sure though.

> You're supposed to know that as "maintainer"...

Joke or attack?
Currently you are taking my minor mistakes, blowing them up out of proportion to use in personal attacks. I have been very tolerant of your obsessive personal hate campains in the past. Your abrasiveness towards people is so ridiculously over the top i often can't take it seriously and it makes me laugh. Please chill out you're only embarassing yourself. I value your input here, you really helped with development of biomes, so i hope you become more pleasant.

**Comment by kilbith** [comment]
If you believe that an operand influence the performances, indeed this question your ability for reviewing a code, excuse me. In this context >15 is discarded if such level doesn't exist, so there's no difference.

About the "attack", you got righly the same remark by other devs already... Stating that I hate you is funny as I personally impulsed your introduction as MTG maintainer (ask nore for confirmation) and I'm always willing to help you.

**Comment by paramat** [comment]
Understanding the fundamental process of a computer enough to know that >= is identical in time to == is fairly deep stuff, i wouldn't consider that a requirement for being a dev.

'hate campaign' is what it feels like, maybe you're not even concious of it, you did this to me before about a year ago. Although you are generally unpleasant to everyone very often, you do seem to focus on certain people sometimes. Someone else here has had an experience of a long series of personal and sometimes really nasty attacks from you.
I have been very tolerant for many months, perhaps too much, but currently feel you need someone to stand up and point put what you do so you can think about it.

**Comment by kilbith** [comment]
You feel wrongly, this is my normal state. About the "someone else" story -> not your business, you ignore some ins and outs.

Anyways I'm stopping this discussion here as it's offtopic. I'm willing to settle this on IRC and apologize if I hurt you.

**Comment by paramat** [comment]
Enough said i think, apologies to all for getting so wound up, i'll now delete my posts.

**Comment by kilbith** [comment]
Cleared too.

**Comment by sofar** [comment]
Pushed with "== 15" changed. This should be merged as-is - I don't see any unaddressed or open comments remaining.

**Comment by paramat** [comment]
:+1:

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
32bdb9a393754464d9baece64e1a3e93d0e29981

**Pull request closed without merging**
