### PR TITLE
Add sandstone wall to Walls mod

### PR DESCRIPTION
**Pull request by vlapsley**
Adding sandstone as a building material for the Walls mod.

### CODE REVIEW

**Comment by kilbith** [comment]
:-1: See : https://github.com/minetest/minetest_game/issues/934#issuecomment-197345963

**Comment by paramat** [comment]
Screenshot?

**Comment by C1ffisme** [comment]
Even if we don't like it, we might as well see it.

**Comment by vlapsley** [comment]
screenshot_20160402_075722

Inspiration from here:
sandstone_wall

**Comment by kilbith** [comment]
It confirms what I said : that kind of walls is not single-piece. It's cobbly.

**Comment by PilzAdam** [comment]
I agree with @kilbith, :-1:.

**Comment by Fixer-007** [comment]
Sandstone is not cobbly by design, sandstone is made of compacted sand particles:
http://www.wallvision.com.au/wp-content/uploads/2013/11/bigstock-Stone-tile-wall-pattern-backgr-12363788.jpg
They break it in parts or saw them and then build walls with cement or even without.

**Comment by C1ffisme** [comment]
What about sandstone brick as a wall? After seeing those pictures, those look more like bricks than smoothly carved stone.

**Comment by vlapsley** [comment]
Using sandstone brick as the source material allows me to create something like this:

screenshot_20160402_123551

**Comment by DonBatman** [comment]
I already have a mod for this plus other stones and bricks. The api makes it easy. Maybe keep walls mod with only a few and have mods so people can choose the ones they want.

**Comment by C1ffisme** [comment]
@vlapsley Hmm... Looks promising, the texture might need tweaking, though.

**Comment by paramat** [comment]
Sandstone brick doesn't look good as wall. Because sandstone is often sawn into large chunks i think it's reasonable to have huge blocks as in the first screenshot, that looks good to me. It would be consistent to have walls for each major stone type present in biomes.

**Comment by sofar** [comment]
This is something for mods, IMHO.

**Comment by sofar** [comment]
@paramat mossy cobble blocks can be obtained in survival mode, so why not allow people to craft something with it? It should be kept.

**Comment by paramat** [comment]
Yes let's keep mossycobble wall.

**Comment by sofar** [comment]
There's already a mod out there that offers this wall and more:

https://github.com/minetest-mods/mywalls

**Comment by paramat** [comment]
Well, that's irrelevant. We have fences for every wood type, and walls for every mapgen stone type except sandstone, so seems a strange omission.

**Comment by sofar** [comment]
We don't have walls for default:stone, nor default:desert_stone or default:obsidian, which are all stone.

I initially submitted this mod with walls for all materials, but people were not supportive of that, so I changed it to cover all the "cobble" materials. Now we're redoing the entire discussion again, but it's moot, since it was *accepted* and *merged* already with a proper discussion, and *only recently*.

Let this sit for a release or two, first, *then* come and discuss it again.

Ref: original PR thread - #796

**Comment by paramat** [comment]
Okay, i don't feel strongly about it. By mapgen stone type i mean those types occuring in large amounts.

**Comment by Gael-de-Sailly** [comment]
I think that the most important material for walls is not stone or cobble, it's stone bricks.

**Comment by paramat** [comment]
The brick textures look wrong as walls.
I've removed my +1 for this as am neutral.

**Comment by paramat** [comment]
Just realised this has 3 -1s, PIlzAdam, sofar and myself, closing.

**Pull request closed without merging**
