### PR TITLE
Default: Add river water textures. New obsidian brick texture

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150530_072925

^ C++ river mapgen in development using my texture submission.

River water (using the existing water textures) was recently added as the fourth base terrain node after air, stone and water. Being such a fundamental node with different properties to normal water it should have an individual texture. The hue has been rotated to create a slight turquoise hue, post_effect_colour has also been altered to match. Working on a c++ river mapgen i am really noticing how unsuitable the normal blue texture is for rivers and highland lakes.

screenshot_2294801278

^ Screenshot from watershed mod as a comparison of normal water (right) and my texture submission (centre).

### CODE REVIEW

**Comment by Novatux** [comment]
Looks good

**Comment by kilbith** [comment]
This allows to distinguish it from the ocean's water and is _more realistic_™ :+1: 

You could use the texture modifiers applied to the current water textures (whether by `[brighten` or `[colorize`) instead of creating new ones.

**Comment by ExcaliburZero** [comment]
This looks good! :+1:

**Comment by paramat** [comment]
Lol kilbith =)

**Comment by C1ffisme** [comment]
:+1: Looks good!

**Comment by paramat** [comment]
450px-sorapis_055

Here's a beautiful real world example of turquiose highland water, Lago Sorapiss at an elevation of 1925m.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Added the approved new obsidian brick texture to this PR.

**Comment by paramat** [comment]
40e2b945e33fff87c50cd304d2c253e1e85d13c7

**Comment by jordan4ibanez** [comment]
Wow that looks really nice

**Pull request closed without merging**
