### PR TITLE
Default: Tune grass and side texture

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160323_002741

^ Submitted

screenshot_20160323_210338

^ Current

benrorig_cn24_h93_s54_ln23_128

^ Submitted

default_grass_0413_128

^ Current 0.4.13

default_grass0410_128

^ 0.4.10

A tuning of the grass texture, addressing the mistakes i made in the current texture.
Less contrast and colourised to a single hue, the brightness and saturation is kept similar to our 0.4.13 and 0.4.10 textures.
Side texture has the same structure.

### CODE REVIEW

**Comment by DonBatman** [comment]
That means I have to redo mypaths, But I do like the look!

**Comment by C1ffisme** [comment]
@paramat Actually, the old texture is from 0.4.9. (Unless I installed a dev version when getting 0.4.10).

**Comment by kilbith** [comment]
No, too smooth for grass. Looks like billiard cloth.

Your patterns are good though.

**Comment by PilzAdam** [comment]
And here we are again with a new grass texture...

**Comment by MT-Modder** [comment]
I get that things can always be improved but it seems like we get a new grass texture every couple months.

As @kilbith said it's just a little too smooth compared to the current texture, otherwise it looks good.

**Comment by C1ffisme** [comment]
@kilbith Is that such a bad thing?
screenshot_20160323_105141

The texture could be a bit smoother, so that it looks a bit less rough and sandy, and more plant-like.

**Comment by paramat** [comment]
It's the exact same noise pattern.
The high contrast is what makes the current grass ugly for me.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
Meh, removing my own approval and adding WIP, i might be able to do better than this. No rush as can be done dring freeze.

**Comment by kilbith** [comment]
Add your approval, this is legit.

**Comment by Ferk** [comment]
Honestly I prefer having contrast as it is now. It blends better with the tall grass nodes. And doesn't have such sharp transition in the side texture.
Also it makes a difference when you enable shaders, you get some relief.

Maybe I grow used to the current texture though. But I don't understand whats so wrong with it.

**Comment by paramat** [comment]
I'd like to try using a completly new noise pattern, there is something about this one that i don't like.
I think i can do better.

**Comment by paramat** [comment]
Not happy with this, closing for now.

**Pull request closed without merging**
