### PR TITLE
Add needed tileable flags for grass nodes

### PR DESCRIPTION
**Pull request by RealBadAngel**
No description needed at all. ;)

### CODE REVIEW

**Comment by Ekdohibs** [comment]
Looks good :)

**Comment by RealBadAngel** [comment]
Not allowed to merge until i decide on a license.
Hands off meanwhile.

**Comment by PilzAdam** [comment]
@RealBadAngel oops, I made a copy of this code when you provided it as LGPL, which means I am allowed to share it as LGPL :-p

**Comment by paramat** [comment]
Odd, this commit contains some already-merged changes to snow depth and dry long-grasses.

**Comment by kilbith** [comment]
oh wow, wtf ? merge that right away before the release please (at least for the tiling part).

If  `tileable_vertical = false` is not added to some nodes, it causes a tiling shit with the bumpmapping.

**Comment by RealBadAngel** [comment]
@paramat you can merge this

**Comment by RealBadAngel** [comment]
damn, it really has some other changes in

**Comment by paramat** [comment]
Closing as a new PR is being prepared.

**Pull request closed without merging**
