### PR TITLE
Add vessels shelf

### PR DESCRIPTION
**Pull request by kilbith**
The vessels set should be completed by its own shelf which can store... the vessels :)

It goes well with the bookshelf for decoration (eg. in the kitchen).

vesselshelf

### CODE REVIEW

**Comment by RHRhino** [comment]
:+1: This could be also useful for potion mods

**Comment by MT-Modder** [comment]
What a great idea! Thanks Kilbith. :+1:

**Comment by nerzhul** [comment]
:+1:

**Comment by C1ffisme** [comment]
:+1:

**Comment by Wayward1** [comment]
I like it!

**Comment by C1ffisme** [comment]
Actually, I think the newest block is straw, but even then, straw is just added because it's dumb not to have it. I think it's about time we started going all 0.4.6 again, and adding a lot of new stuff. I want to see this and many more new blocks enter minetest_game.

Just because minetest_game is a modding base, dosen't mean we can't have some fun in it. And if it is a base for mods, then minetest should have more things to support the mods.

**Comment by LeMagnesium** [comment]
:+1: for stocking vessels.
> This could be also useful for potion mods

 But if I read the code right, it couldn't stock potions, but it's not a problem for minetest_game itself.

**Comment by kilbith** [comment]
@LeMagnesium It can store any node that has `vessel=1` in the node def.

**Comment by LeMagnesium** [comment]
So it's even better, ready to be supported in potions mods.

**Comment by C1ffisme** [comment]
Question : Don't you need to add your name and texture to the texture licenses?

And please, don't use a free-culture license. Just use Creative Commons.

**Comment by LeMagnesium** [comment]
I don't know about you, but a shelf that could stock bottles and vessels is at its right place with them in the creative inventory : it stocks vessels, why putting it in default? Indeed, "why not putting it in default"? But it seems rather logic to put **vessels**'s shelfs in **vessels** mods.

**Comment by C1ffisme** [comment]
True, true.

**Comment by Ombridride** [comment]
I agree with Mg

**Comment by C1ffisme** [comment]
Why does this have Low priority _and_ enhancement? Why not just put the label "low priority enhancement"?

**Comment by Amaz1** [comment]
This is a brilliant idea! :+1: 
@C1ffisme If someone removed the vessels mod, and this node was in default, it would be pretty wierd for there to be something that was related to a removed mod to be in defualt... So I think this belongs to the vessels mod.
And regarding the last block that was added to mt_game, I think that would be beds, added 9 days ago!

**Comment by C1ffisme** [comment]
Yeah, maybe it's just me.

Alright, let's just add this. We haven't done much block adding, anyway. Just because minetest_game is a modding base, dosen't mean that it has to be boring. This would improve minetest_game's fun.

MERGE IT! MERGE IT! MERGE IT!

**Comment by BlockMen** [comment]
> MERGE IT! MERGE IT! MERGE IT!

Do you really think that would speed things up?

**Comment by C1ffisme** [comment]
I don't know. I'm eager.

**Comment by PilzAdam** [comment]
Why not use `group:vessel` in the crafting recipe?

**Comment by 0-afflatus** [comment]
:+1: add to vessels.

**Comment by kilbith** [comment]
@PilzAdam Done.

**Comment by PilzAdam** [comment]
@kilbith in `allow_metadata_inventory_move` you still use the hardcoded vessel nodes; use `group:vessel` there, too. Also remove the `vessels_nodes` table then.

**Comment by kilbith** [comment]
@PilzAdam Done (again).

**Comment by Novatux** [comment]
Looks good :)

**Comment by PilzAdam** [comment]
You should use `minetest.get_item_group(stack:get_name(), "vessel") ~= 0` instead of `stack:get_name() == "group:vessel"`.

**Comment by kilbith** [comment]
@PilzAdam Done.

**Comment by BlockMen** [comment]
https://github.com/minetest/minetest_game/commit/3f2e35e8272ebc7a50a9e7af01ffc365558d3408

**Pull request closed without merging**
