### PR TITLE
Mgv5/7 biomes: Add shallow dirt waters

### PR DESCRIPTION
**Pull request by paramat**
Dirt waters are more suitable for waterlilies
Add dedicated dunes biome in coniferous forest
Papyrus: use dirt base
Force-place roots on mapgen tree schematics
Tune some humidity points to improve voronoi cells
Add random rotation to jungle trees

See #686 
Shallow dirt waters are added to deciduous forest and savanna biomes, the seabed changes to sand below this. This makes lakes and pools dirt while keeping deeper ocean sandy. The dirt pools look much more natural for waterlilies. They are called 'swamps' to be consistent with the rainforest swamp biome name.
Dunes (sand with long grasses) were present in most biomes, now they are a dedicated biome in coniferous forest areas.
Now that savanna has dirt waters papyrus with it's sandy base looks out of place in dirt swamps, the base is now soil again (which is more suitable for papyrus to grow from).
Now that sapling-spawned trees are separate schematics i can now force-place the lowest root nodes of mapgen trees.
The shape of the heat/humidity voronoi cells needed tuning, humidity points have been moved slightly for some biomes.
Random rotation was missing from jungle trees.

### CODE REVIEW

**Comment by paramat** [comment]
Now that savanna has dirt waters papyrus with it's sandy base looks out of place, i will change the base back to soil and keep it in savanna only (removed from deserts).

**Comment by kilbith** [comment]
> Force-place roots on mapgen tree schematics

Wait, this idea has been declined in the past, isn't it ?

**Comment by paramat** [comment]
Yes, declined for sapling-grown trees, so they do not consume dirt nodes on a skyblock server. We now have separate sapling-grown tree schematics that only replace the sapling and nothing else.
The mapgen jungle and pine trees already force-place roots by necessity, jungle trees need to replace water in swamps, pine trees need to penetrate snowblocks to reach the dirt below. This commit just forces appletree and acacia roots also.

**Comment by paramat** [comment]
Approval http://irc.minetest.ru/minetest-dev/2015-10-02#i_4412528

**Comment by paramat** [comment]
2119054a95d9fe711e8ee73fb3ed18fcbbb0cd3f

**Pull request closed without merging**
