### PR TITLE
Add straw

### PR DESCRIPTION
**Pull request by kilbith2**
_(I re-opened it because I lost my password on kilbith3, sorry)_

Copy of the PilzAdam's commit (https://github.com/PilzAdam/minetest_game/commit/97bef0f747c0c24bf07dc6033f002a3e91767858) with a different crafing recipe (9 wheats is too expensive).

d8ca8bc0-8abd-11e4-98e7-5ab82b407e19

### CODE REVIEW

**Comment by PilzAdam** [comment]
I dislike that it drops wheat. It's annoying when you want to dig and replace the straw somewhere else.
Other blocks of condensed material (i.e. the ore blocks) drop themselves instead of the material they are made out of, too.

**Comment by kilbith2** [comment]
@PilzAdam : right. Updated.

**Comment by CraigyDavi** [comment]
> (I re-opened it because I lost my password on kilbith3, sorry)

Instead of creating multiple accounts why not use different branches? `git checkout -b new-branch-name`

**Comment by paramat** [comment]
Good addition yes please.
Please could you add:
is_ground_content = false,
between tiles and groups? This way if placed by a mod at mapgen time caves will not eat holes in it.
Also perhaps the grass sound would be softer and more suitable?

**Comment by kilbith2** [comment]
Done.

**Comment by PilzAdam** [comment]
You should use tabs to indent, not spaces (you used spaces in the is_ground_content line).
The dev who merges this can fix this, though (if you don't want to).

**Comment by kilbith** [comment]
Hmm, no one has noticed... but 4 wheats as recipe is already used for the flour. So the flour is craftable with 3 wheats instead of 4 now.

**Comment by thatgraemeguy** [comment]
I'm not sure that changing flour's recipe is the best fix, wherever someone is using automation to make flour they'd end up with a lot of straw and perhaps not be aware of it for a while.

**Comment by kilbith** [comment]
I don't know a better solution... and I don't really want to debate on a so futile change.

**Comment by MT-Modder** [comment]
Just do this: 9 wheat gives you three straw and one straw gives you three wheat. I don't remember who suggested this but it wasn't me :smiley:

**Comment by ShadowNinja** [comment]
@MT-Modder :+1:

**Comment by kilbith** [comment]
OK finally I followed the recommendation of @MT-Modder, which is the best IMO... and recovered the previous flour recipe.

**Comment by sfan5** [comment]
hm. I think the texture is a bit too dark at the top and bottom.

**Comment by Novatux** [comment]
https://github.com/minetest/minetest_game/commit/5d8b2442ce6238bb1bf662166341f6254e911ef5

**Pull request closed without merging**
