### PR TITLE
Default: Add 'snowy pine tree from sapling' schematic

### PR DESCRIPTION
**Pull request by paramat**
Add function to detect nearby snow to enable snow on sapling-grown pine trees
Correct 'place schematic' rotation parameters to "0" or "random"
////////////////////////////////

This already happens in mgv6, adding this feature to all other mapgens.
Snow detection is moved from mgv6 pine code to a seperate function.
Sapling pines grown in non-snowy areas are identical to before.
In snowy areas they are near-identical to mapgen snowy pines:

screenshot_20160227_174733

Because the snow nodes need support frpm below the top layer of branches is not fully random but designed to look random, and random rotation is used instead to vary appearence.

### CODE REVIEW

**Comment by MoNTE48** [comment]
:+1: It is very annoying when I get into the forest and falls on top of me, a lot of snow! :)

**Comment by kilbith** [comment]
- Are the snow nodeboxes removed from the trees ? (you shared your intention to do so recently).
- If yes, can you extend the scope of this PR and phase-out the nodeboxes from snowy forests ? (you know the reasons why).

**Comment by paramat** [comment]
Snow nodeboxes remain at the moment, perhaps another PR for changing that. They could possibly be replaced with snowblocks as biome 'dust' if this still looks good.
The snow nodeboxes could be removed from mgv6 snowy pines, again perhaps another commit.

**Comment by Napiophelios** [comment]
You need to adjust the tiles to avoid the xray effect when looking up thru the pine needles

`tiles = {"default_snow.png", "default_snow.png^default_pine_needles.png",
		"default_snow.png"},`

I would also suggest creating a texture for this, it would look much nicer

screenshot_20160225_134553

**Comment by MoNTE48** [comment]
@Napiophelios but it looks very good.

**Comment by Napiophelios** [comment]
Needs more snow :)
screenshot_20160225_141549

**Comment by MoNTE48** [comment]
@Napiophelios WOOOOW!!! +100500 It looks divine.

**Comment by Napiophelios** [comment]
Default textures dont look bad with modifiers either

`tiles = {"default_snow.png", "default_snow.png^default_pine_needles.png", "default_snow.png^default_pine_needles.png^default_snow_side.png"},`

screenshot_20160225_142419

**Comment by MoNTE48** [comment]
@Napiophelios, Let's see what will @paramat and others, but it is very beautiful and that's what I'd like to see

**Comment by paramat** [comment]
screenshot_20160226_015533

Having problems, looks like 'allfaces optional' only works if all 6 tiles are identical. when fancy leaves is enabled it seems to use the top tile for all 6 faces.

**Comment by kilbith** [comment]
@Napiophelios proposals look much better :+1:

**Comment by 0-afflatus** [comment]
What is the issue with snow nodeboxes? Could someone briefly explain or point me to a discussion?

**Comment by paramat** [comment]
They reduce FPS a little and can't have smooth lighting.
However there's a good chance we'll keep them, especially with speedup due to VBO.

**Comment by paramat** [comment]
Complete and tested.
Having problems with random rotation not working for sapling-grown pines.

**Comment by Ekdohibs** [comment]
Looks good!

**Comment by paramat** [comment]
5d28040915f9b23aad008553b51a9db5b2bee4dd

**Pull request closed without merging**
