### PR TITLE
Books: Add support for multiple pages

### PR DESCRIPTION
**Pull request by kilbith**
Fixes https://github.com/minetest/minetest_game/issues/938

Adds the support for multiple pages + fancier title.

screenshot_20160316_215610

Cc: @ShadowNinja @kaeza

### CODE REVIEW

**Comment by Fixer-007** [comment]
Nice! Word wrap is working?

**Comment by C1ffisme** [comment]
Looks good.

Nice book.

**Comment by kilbith** [comment]
> Word wrap is working?

If you mind yourself to press Enter (= new line) at the border of the field, then yes, it wraps correctly.

If it bothers too much the players to not have an auto-wrapping, then I could bring back the `textarea`, but it looks uglier than a `label` and books would be writtable for everyone.

**Comment by sofar** [comment]
> and books would be writtable for everyone.

why is that?

**Comment by kilbith** [comment]
Because it's the nature of `textarea`, you can edit the text with it.

**Comment by Ferk** [comment]
Last time I checked you could make the textarea read-only by leaving the “name” and “default” arguments empty and using the “label” as text. Was that changed in latest version?

      textlist[1,1;6,3;;Once upon a midnight dreary;]

The only problem with the textarea and the reason it was changed to list was that it didn't show any scrollbar. But that would be overcomed with your pager now.

**Comment by kilbith** [comment]
I'm going to use that. Thanks for the hint.

**Comment by paramat** [comment]
Pages are much better than scrollbars.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by paramat** [comment]
b57dd0f9b2ae22ce4198b9e30531cf9323969e41

**Pull request closed without merging**
