### PR TITLE
light gunpowder with flint and steel

### PR DESCRIPTION
**Pull request by cdqwertz**
With this pr, you can light gunpowder with flint and steel.

### CODE REVIEW

**Comment by kilbith** [comment]
The idea is good, but the code needs some work. And you should add `tnt?` in `depends.txt`.

``` Lua
if pt.type == "node" then
        if not minetest.is_protected(pt.under, player_name) then
                 if minetest.get_node(pt.under).name == "tnt:gunpowder" then
                          minetest.set_node(pt.under, {name="tnt:gunpowder_burning"})
                          minetest.get_node_timer(pt.under):start(1)
                 elseif minetest.get_node(pt.above).name == "air" then
                          minetest.set_node(pt.above, {name="fire:basic_flame"})
                 end
        else
                 minetest.chat_send_player(player_name, "This area is protected")
        end
end
```

**Comment by cdqwertz** [comment]
@kilbith That doesnt work, because tnt has the fire in its depends.txt

**Comment by kilbith** [comment]
By the way it'd be simpler and better to implement that in the `tnt` mod at that [line](https://github.com/minetest/minetest_game/blob/master/mods/tnt/init.lua#L300).

All you need to do is : 

``` Lua
local wielded_item = puncher:get_wielded_item():get_name()
if wielded_item == "default:torch" or wielded_item == "fire:flint_and_steel" then
```

It won't place a flame as it will prevented soon for non-`flammable` nodes in my other PR.

**Comment by cdqwertz** [comment]
But this pr isnt merged yet, is it?
I tried that too, It didnt work.

**Comment by kilbith** [comment]
Then change the callback to `on_rightclick`. Tested, it works.

**Comment by cdqwertz** [comment]
But then, the flint and steel wouldn't break.

**Comment by paramat** [comment]
I'd prefer this done the simpler way in tnt mod, even if it doesn't wear the flint and steel.

**Comment by paramat** [comment]
Needs rebasing on recent fire mod changes.

**Comment by PilzAdam** [comment]
Using `on_punch` would be quite inconsistent with the current control scheme.

Wearing out the flint and steel is definitely needed.

**Comment by cdqwertz** [comment]
@paramat Ok, I will rebase this :)

**Comment by sofar** [comment]
I'm a tool wear crusader, and therefore I support pilzadam's statement: tools should wear out. :)

**Comment by cdqwertz** [comment]
Rebased!

**Comment by sofar** [comment]
This isn't rebased properly. There are now 4 commits in this PR, including a merge commit, and there should be only one.

**Comment by cdqwertz** [comment]
Should I open a new Pull Request?

**Comment by sofar** [comment]
no, just fix your local branch up and push again.

you could just do something like this: 

```
git diff origin/master > patch
git reset --hard HEAD~4
git pull --rebase
patch -p1 < patch
git commit -a
git show # and if this looks OK, then do:
git push -f
```

**Comment by paramat** [comment]
I might rework this or include it in #1076

**Comment by paramat** [comment]
Implemented in #1076 so closing, PR is a mess anyway :]

**Pull request closed without merging**
