### PR TITLE
Strengthen obsidian glass

### PR DESCRIPTION
**Pull request by tenplus1**
Obsidian glass should be harder to break than it is just now...

### CODE REVIEW

**Comment by RHRhino** [comment]
makes sense :+1: 
(But why is the new group level=2 instead of oddly_breakable_by_hand? Has that changed or is that a "typo"?)

**Comment by C1ffisme** [comment]
That sounds like a good idea, In fact, we should make it blast-proof too, so that you can use it for bomb shelthers!

**Comment by tenplus1** [comment]
RHRhino: bope, not a typo...  If obsidian glass is strengthened then the ability to dig it by hand shouldn't be there...

**Comment by rubenwardy** [comment]
IRL obsidian is pretty weak. But this isn't real life and obsidian in game is strong so obsidian glass should be strong too.

**Comment by Jordach** [comment]
@rubenwardy - obsidian IRL can be very hard to break. It just depends on
the formation. Assume that MT uses the hardened form.

**Comment by kilbith** [comment]
IRL, obsidian is hard but brittle. Great hardness doesn't mean that it's hard to break.

(I personally carved knives with obsidian)

**Comment by rubenwardy** [comment]
Exactly, kilbith. Like how glass is hard but brittle. I think Jordach was saying that it may not be brittle, though.

**Comment by HybridDog** [comment]
mese is harder than obsidian, isn't it?

**Comment by paramat** [comment]
:-1: For cracky 2 and level 2, this makes it as hard as stone bricks and requiring a tool with a level high enough for obsidian.
However i would +1 just removing 'breakable by hand' so players can't just punch your windows out.

**Comment by 0-afflatus** [comment]
Again gameplay wins over reality. I would support the ability to make 'toughened glass'.

Does obsidian glass even exist in rl?

**Comment by paramat** [comment]
Well obsidian is a 'volcanic glass' and exists in clear and coloured forms, but sheets of obsidian-infused glass i'm not sure about. It probably wouldn't be any tougher, i just like the idea of having a glass type not punchable.

**Comment by paramat** [comment]
Needs squashing.

**Comment by tenplus1** [comment]
paramat: krock squashed it for me, could you add it already :)

**Comment by paramat** [comment]
Okay cracky 2 seems ok to me now to make it tougher than normal glass :+1:

**Comment by ShadowNinja** [comment]
Obsidian glass was originally added as a compromise between the "obsidian shatters easily" crowd and the "MC uses hard obsidian so we should too" crowd.
IMO they should both be realistically fragile.

**Comment by tenplus1** [comment]
The general idea was to make it so that players required a tool to break obsidian glass which the latest changes handle fine.

**Comment by paramat** [comment]
Perhaps it should be cracky = 3? Otherwise its harder than stone.
Removing 'breakable by hand' seems enough change by otself.

**Comment by tenplus1** [comment]
@paramat as it stands the change will work for the better and players will craft obsidian glass as an alternative so it's not easily broken by noobs.  Please add.

**Comment by PilzAdam** [comment]
I'm not sure whether it should be `cracky=2` or `cracky=3`, but it should definitely not be breakable by hand.

**Comment by paramat** [comment]
I'll +1 if it's changed to cracky = 3.

**Comment by tenplus1** [comment]
@paramat - setting cracky to 3 still feels too quick to dig whereas 2 feels like it's obsidian glass and not normal glass being dug up with a pick.

**Comment by PilzAdam** [comment]
@tenplus1 you can control the dig time by setting a `level` group, too.

**Comment by tenplus1** [comment]
@PilzAdam - lol, this was originally added but deemed unsuitable at the time so it was removed.

**Comment by paramat** [comment]
Yeah that was me who objected, the level 2 was making it insanely tough.
I know that cracky 3 is the same as normal glass, but removing breakable by hand is what makes the difference, it seems somewhat wrong to have glass tougher than stone. However i don't feel strongly about it if other devs are ok with cracky 2. It seems ShadowNinja would prefer cracky 3 also?

**Comment by tenplus1** [comment]
The changes have been in effect on Xanadu server for a few weeks now and players are happy with the differences in glass types, actively using obsidian glass to make their builds tougher for noobs to get into.  I'd rather the cracky level stay at 2.

**Comment by paramat** [comment]
The difference is only a slightly longer dig time with the same tool, only 'level' would make a significant difference in protecting against other players.

**Comment by tenplus1** [comment]
@paramat - yes, a slightly longer digtime but you MUST use a tool, that's the main difference.

**Comment by paramat** [comment]
Sfan5 had no opinion on this. ShadowNinja sounds like they would like a less tough option, PilzAdam is neutral on cracky but agrees to removing breakable by hand. So, you can get 2 approvals with cracky = 3 .. =)

**Comment by paramat** [comment]
Thanks! :+1:

**Comment by paramat** [comment]
@PilzAdam > I'm not sure whether it should be cracky=2 or cracky=3, but it should definitely not be breakable by hand.

I'll assume this is a +1.

**Comment by paramat** [comment]
Needs rebasing. Also please could you add spaces either side of the 2nd '='?
@PilzAdam is your comment a +1 now this is ```groups = {cracky = 3},```?

**Comment by PilzAdam** [comment]
@paramat I guess; I'm not really sure, but if others are comfortable with it then it's ok.

**Comment by sofar** [comment]
I'm ok with removing the oddly_breakable_by_hand group.

**Comment by tenplus1** [comment]
@paramat REBASED!

**Comment by paramat** [comment]
Approval from nore http://irc.minetest.ru/minetest-dev/2016-04-11#i_4582023

**Comment by paramat** [comment]
6e1a3297636bc0e20d623f0a3214144158fddb66

**Pull request closed without merging**
