### PR TITLE
add node copper patina

### PR DESCRIPTION
**Pull request by pithydon**
Good for building things like the statue of liberty.

### CODE REVIEW

**Comment by kilbith** [comment]
After the “_gnucydur_”, the “_copperpatina_” ! I'm loving these wacky new ore proposals...

**Comment by rubenwardy** [comment]
Except that gnucydur is fictional, whereas patina actually exists: https://en.wikipedia.org/wiki/Patina

**Comment by rubenwardy** [comment]
I feel like this is the realm of mods, though.

**Comment by sofar** [comment]
I'd rather someone spent some actual time fixing the current ore tier system than this.

No gameplay value, purely ornamental.

**Comment by C1ffisme** [comment]
I like the idea, but I'm not sure if this should go in Minetest Game, since we already have greenish materials. (Although, we don't have a greenish metallic material.)

@sofar I would like it if Wooden tools were removed, and stone tools (Made from stones on the ground) were the first tier. Then copper or bronze (Tin? Maybe it could be that green metal?) tools, then iron/steel tools, then mese and diamond tools. (Maybe not even mese, mese could be used for something else. A lighter version of mesecons, maybe?)

**Comment by sofar** [comment]
@C1ffisme probably should do a separate issue on the topic, anyway

**Comment by C1ffisme** [comment]
@sofar Yeah.

**Comment by paramat** [comment]
:-1: I feel this is too specialised for MTGame, more a mod thing, we tend to only have very fundamental materials.

**Comment by 0-afflatus** [comment]
Nice idea but could be done much better in a mod, it should be part of a generic weathering system that could include lichen on rocks, rusting on iron, woodworm etc. using lbms to control the decay. Something like, and compatible with, sofar's sedimentology. This is really the realm of subgames.

**Comment by tobyplowy** [comment]
@pithydon this is an Amazing Idea. More building blocks I Love It! (Btw) is it Possible to get The Bucket back

**Comment by tobyplowy** [comment]
@pithydon this is an Amazing Idea. More building blocks I Love It! (Btw) is it Possible to get The Bucket back @sofar we really need to add more gameplay to Minetest but more decoration blocks can't hurt.

**Comment by C1ffisme** [comment]
The recipe for this is really un-balanced, if you wanted to make a statue in survival mode, you would need a lot of water. A better way to do this would involve some kind of weathering like @0-afflatus talked about. However, we don't have weather, or any other kind of decay. (Except for mossy cobblestone. Maybe something similar could be used?)

**Comment by paramat** [comment]
You could submit this to the very popular mod 'Moreblocks'.

**Comment by pithydon** [comment]
I submitted it to 'Moreblocks', you may want to close this.

**Comment by sofar** [comment]
This was merged in moreblocks.

**Pull request closed without merging**
