### PR TITLE
word-wrap book text

### PR DESCRIPTION
**Pull request by tenplus1**
This change word-wraps text when reading a book and adds a close button for touch-screen users...

### CODE REVIEW

**Comment by kilbith** [comment]
Currently : https://lut.im/3HV07URM/2sUIRwQU
With your patch : https://lut.im/tshm7c7Y/oFpcPZMe

Must be merged ASAP.

**Comment by tenplus1** [comment]
You should see books in Xanadu server, has paper background and all :)

**Comment by C1ffisme** [comment]
Good!

**Comment by est31** [comment]
merged in 8b4a92ef2da4b4ef9bb2be7ce4c532a7a7563795 without the close button though. Android users can use the OS provided back button to exit menus.

**Comment by rubenwardy** [comment]
@est31 the hardware back button isn't a standard on Android devices AFAIK, it is possible to get ones without them. The X button does look better - although I agree it shouldn't be done by a mod.

**Comment by est31** [comment]
If they don't have a hardware back button, doesn't the OS emulate one on the screen? Or is that emulated one not shown?

**Comment by est31** [comment]
In [this link](http://developer.android.com/training/implementing-navigation/temporal.html), google writes:
> All Android devices provide a Back button [...], so your app **should not add a Back button to the UI**.

If there are devices where the fullscreen hides the system bar, we should find methods to get it in again.

**Comment by rubenwardy** [comment]
Okay, my bad. I was probably thinking about the menu button - Google recently added a menu icon to chrome on android, I was told because it's non standard. (I'm talking about [this](http://cdn5.howtogeek.com/wp-content/uploads/2014/03/chrome-view-synced-open-tabs.png))

Also, many apps add back buttons, [Google Handout included](https://cdn0.vox-cdn.com/thumbor/xONQsBuiI7_6mtGWYcpgbBLr7r4=/cdn0.vox-cdn.com/uploads/chorus_asset/file/2535986/hangouts-new.0.jpg) :P

**Comment by est31** [comment]
Thats an [up](http://developer.android.com/design/patterns/navigation.html) button.

**Comment by rubenwardy** [comment]
Oh. Didn't know that :D

**Pull request closed without merging**
