### PR TITLE
Add lilypads

### PR DESCRIPTION
**Pull request by Calinou**
They rotate randomly when generated. Technically, they use schematics and are a decoration.

Originally made by @kilbith.

Lilypads

### CODE REVIEW

**Comment by PilzAdam** [comment]
Why are they spawned by schematics?
Why don't they rotate randomly when placing them by hand?
Shouldn't you make them `liquid_pointable=true` to be able to place them on water?
Why can you place them outside of water?
The screenshot suggests that they spawn in the dessert biome; that doesn't seem right.

**Comment by kilbith** [comment]
> Why are they spawned by schematics?

Only way to spawn things on water with `minetest.register_decoration`. The schematic includes one lilypad and 2 water sources below (inspired from papyrus in mgv7).

> Why can you place them outside of water?

Why can you place torches inside water ?

> The screenshot suggests that they spawn in the dessert biome; that doesn't seem right.

They tend to spawn in/near wetlands actually. But @paramat might have better parameters.

**Comment by PilzAdam** [comment]
> > Why can you place them outside of water?
>
>Why can you place torches inside water ?

Really good point.

**Comment by kilbith** [comment]
Just in case...

``` Lua
on_place = function(itemstack, placer, pointed_thing)
     if minetest.get_node(pointed_thing.under).name ~= "default:water_source" then
            return
     end
end
```

**Comment by paramat** [comment]
> Only way to spawn things on water

Correct.

> Why don't they rotate randomly when placing them by hand?

If that's possible it would be nice.

> The screenshot suggests that they spawn in the dessert biome; that doesn't seem right.

I will need to use a different registration for mgv5/mgv7, that defines the biomes.

**Comment by kilbith** [comment]
A side-note : texture by Gambit.

**Comment by paramat** [comment]
Okay. Gambit is very talented.

**Comment by paramat** [comment]
Oh and it should be called 'flowers:waterlily' to name it as a whole, the pad is just the leaf, see IRC discussion.

**Comment by paramat** [comment]
I'm willing to work on and open a new PR for this if the authors are too busy, i would have to do the mapgen integration anyway. Any other devs approve of lilies?

**Comment by PilzAdam** [comment]
@paramat yes, if the remarks in my previous comment are considered.

**Comment by paramat** [comment]
New commit merged 4bb9652c0f6c1736ca325ed94aaff10be9a11b47

**Pull request closed without merging**
