### PR TITLE
Compress textures

### PR DESCRIPTION
**Pull request by MoNTE48**
Use PNGOUT, OptiPNG and DeflOpt. Compress ~75 kb without loss of
quality.
No visual changes.
Texture compression helps reduce the size of the code (as well as the whole game) and also slightly increases the performance. I use these tools for about 3 years, no problem.

### CODE REVIEW

**Comment by kilbith** [comment]
>  and also slightly increases the performance

Wrong, that's a common belief. Compressed formats like PNG have to be uncompressed first at initialization. It's infinitesimally slower than non-compressed files / formats (like BMP or TIFF).

For 75 KB gained, it's not worth merging it.

**Comment by asl97** [comment]
imo, the image is compress more than enough already.

75KB might be gain if people just download the subgame without the git repo but 142KB would be permanently added to it.

**Comment by paramat** [comment]
-1. Texture compression PRs come around often, and textures have already been compressed too many times before, textures are low-res and small already and quality is more important. Also, some texture optimisations can ruin the background colour in leaves textures, which needs to be a chosen colour when 'leaves_style = opaque'.

**Comment by sfan5** [comment]
:-1: This has already been done in the past and saving only 75 KB is not enough to justify this.

**Comment by C1ffisme** [comment]
Honestly, you would save more by clearing your internet history. I'm against this. 75KB does not matter in the slightest. And haven't they been compressed enough?

**Comment by paramat** [comment]
-1

**Comment by HybridDog** [comment]
> It's infinitesimally slower than non-compressed files / formats (like BMP or TIFF).

l think if the uncompressed file takes ~200MB and the compressed one ~283B, loading the compressed one works a lot faster.
If you make a ppm completely black with a big resolution, the png file of it gets loaded immediately.

**Pull request closed without merging**
