### PR TITLE
Default: New darker jungletree_top and junglewood textures

### PR DESCRIPTION
**Pull request by paramat**
e22acfba-3ecf-11e5-8b5f-57b79171af1a by VanessaE, derived from Cisoun's texture

3dcdce3e-3fc1-11e5-8d50-5acf6f46b166 by paramat, derived from Blockmen's wood texture

2cb0c9b2-3fc1-11e5-935b-8887c9ab916f PilzAdam's original dark junglewood texture

See #611
The jungletree_top texture was in the initial commit of #619 and was approved by 2 MTGame devs.

### CODE REVIEW

**Comment by kilbith** [comment]
I put my junglewood here in case if some dev(s) prefer it : 

16fb8a76-400c-11e5-9aa6-b7a045d5c9f2 junglewood

[[Compare here]](https://github.com/minetest/minetest_game/issues/611#issuecomment-129740744)

**Comment by paramat** [comment]
Approval http://irc.minetest.ru/minetest-dev/2015-08-14#i_4364971

**Comment by paramat** [comment]
b7a1426b42de743d07d845086f9f86f4ac845786

**Comment by kilbith** [comment]
Poorly contrasted greenish planks VS. Faithful well-aged planks... but, well, as long as paramat is actively lobbying his stuff, it'll be casually consented for `paramat_game` and never declined, as usual. No wonder why people like [BlockMen](http://irc.minetest.ru/minetest-dev/2015-08-11#i_4360158) are left (including me right now). This game is lost.

screenshot_20150815_132237
screenshot_20150815_132219

**Comment by PilzAdam** [comment]
@kilbith no need to be upset; @paramat doesn't want to harm anyone.

That comparison really shows that the upper texture is too green-ish. The one at the bottom looks better in contrast to the normal wood. @paramat can you change the texture?

**Comment by paramat** [comment]
@PilzAdam my texture was made to be identical in hue and saturation to your original, which you stated you liked and many players wanted to return to. I do agree it's a little greenish but it actually has the same hue value as normal wood. With agreement from other devs i could make it less green while still being just as dark. kilbith's texture isn't dark enough.
kilbith you are rather abrasive, i find it hard to take it seriously =)

**Comment by kilbith** [comment]
> It was approved by 2 other devs so looks like we'll keep it for now.
1. My texture too, and I got more +1 by the regular followers. You didn't even bothered to make a proper comparison and passively occulted my contribution by doing so.
2. Natural green planks simply don't exist, that's just a donkeyshit. The normal wood is rather coyote brown.

**Pull request closed without merging**
