### PR TITLE
Add: New Heart Texture

### PR DESCRIPTION
**Pull request by KevDoy**
Same as before, but added symmetry and slightly more rounded off

[Edit by paramat ..

heart128

Submitted texture.

oldheart128

Current texture.]

### CODE REVIEW

**Comment by sofar** [comment]
Sorry, I had to use the emoticon for that one.

It's very decent. Maybe a bit traditional perhaps. Very not bad at all.

**Comment by KevDoy** [comment]
@sofar Thank you - just felt like the current one needed a bit cleaning up. Didn't want to modify it too much!

**Comment by kilbith** [comment]
I made one just for fun : heart

| Mine | Yours |
| --- | --- |
| capture d ecran de 2016-04-12 11-59-03 | capture d ecran de 2016-04-12 11-48-07 |

Note : there's a grey-ish pixel in yours.

**Comment by tobyplowy** [comment]
i also did one 
heart
heart 12x12

**Comment by MT-Modder** [comment]
:+1: For KevDoy's without the weird gray pixel. (Not kilbith's)

@kilbith I like your's but I find it a bit dark and the pixels "blend" less.

Great work to everyone! The old heart was way too pixelated\choppy.

**Comment by C1ffisme** [comment]
I like @kilbith 's, since it's a bit easier on the eyes.

I also like @tobyplowy 's, since it's a bit more cartoony than the original.

I'm not so sure what @KevDoy changed, though. It looks a bit too much like the texture we have already.

**Comment by KevDoy** [comment]
@MT-Modder  Thanks you!

@C1ffisme I wanted to keep the colors, shading, and everything the same just make it symmetrical and even.

**Comment by sofar** [comment]
Can you fix the gray pixel?

**Comment by KevDoy** [comment]
Sure thing, I can edit the pull request when I get home from work.

heart

**Comment by paramat** [comment]
It'a big improvement. Please could the lower shading be more symmetrical?
IMO ...
From the centre of the shine ...
1. Go 3 pixels leftwards, this pixel should be bright red (unshaded) and the 2 pixels below should be colour-sampled from the mirror-image pixels on the other side of the heart, because they are too dark.
2. Go 2 left, 2 down, this pixel is too dark, it should match it's mirror-image.

**Comment by paramat** [comment]
Our curent grey-shine is a bit weird, it might be possible to make this a red-white blend shine instead of red-grey blend.

(I must admit i think tobyplowy's heart is excellent and my favourite, the white shine is so good.)

**Comment by paramat** [comment]
Added to milestone as our current heart is so bad.

**Comment by paramat** [comment]
KevDoy you can add yourself as the texture author in the README file.

**Comment by KevDoy** [comment]
Will update asap. Will do, thanks!

**Comment by paramat** [comment]
:+1: 
I can see the shine is a blend of red and white, the greyishness seems to be an illusion.

**Comment by paramat** [comment]
heart128

Submitted texture enlarged.

**Comment by paramat** [comment]
@KevDoy are you comfortable with squashing commits? if not we can do this when merging.

**Comment by KevDoy** [comment]
@paramat Haven't done that before - still fairly new to git(hub). Would love some pointers unless it would be easier for you to just do that.

**Comment by sofar** [comment]
git tips: https://forum.minetest.net/viewtopic.php?f=3&t=14262&p=211501#p211501

**Comment by kilbith** [comment]
Shouldn't that be `default_heart.png` to follow naming convention ?

**Comment by paramat** [comment]
I think it's just 'heart' and not a part of default.

Squash seems to have failed, don't worry we can squash this easily for you.

**Comment by KevDoy** [comment]
@paramat I appreciate it. Will look into what I was doing wrong.

**Comment by paramat** [comment]
Looks like the last 2 commits can be deleted, commit 5 is a combination of the first 4.

**Comment by paramat** [comment]
This can be merged during freeze.

**Comment by paramat** [comment]
Approved by sfan5 http://irc.minetest.ru/minetest-dev/2016-04-21#i_4588789 will merge soon.

**Comment by paramat** [comment]
fa43bd8a5668f8ae38bc3f61ce628874014f9b5d

**Pull request closed without merging**
