### PR TITLE
Improved stairs model, v2

### PR DESCRIPTION
**Pull request by ElementW**
v2 of PR #561
Eliminate floating point precision errors (grr!) and have shorter coordinates representation.
Plus strip the Blender prologue and trailing newline.

### CODE REVIEW

**Comment by paramat** [comment]
Thanks will merge soon.

**Comment by paramat** [comment]
Please could you rename the stair object to follow naming conventions? it should be 'stairs_stair.obj'.

**Comment by kilbith** [comment]
@paramat Please test before merging... This model that @gravgun suggests is screwed : 

screenshot_20150710_092226

And how deleting the zero floating improves something ?

**Comment by gravgun** [comment]
@kilbith Works for me though :/
Working stairs model

**Comment by kilbith** [comment]
OK - seems fixed. Can't see any problem now :+1:

**Comment by paramat** [comment]
Thanks to you both.

**Comment by paramat** [comment]
8a7af21e3a55b7f0e7162d8ca0e7d4f2934837b5

**Pull request closed without merging**
