### PR TITLE
Default: New stone brick and desert stone brick textures

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150816_215257

Less similar to Minecraft textures.
More defined shading of bevelled edges.
Missing dark bevel shading added.
Fix discoloured shading of light bevelled edges in desert stone brick.
Mortar has a subtle lightness variation.

stone_brick_vd25_vl25_mmid_rgb256

^ Submission

default_stone_brick_current256

^ Current

desert_stone_brick_vd25_vl25_mdark_rgb256

^ Submission

default_desert_stone_brick_current256

^ Current

### CODE REVIEW

**Comment by kilbith** [comment]
:+1: I really like them. The relief effect is nearly perfect.

**Comment by VanessaE** [comment]
:+1:

**Comment by sfan5** [comment]
very nice :+1:

perhaps make the desert stone brick texture a little different from the other one (not only different color)

**Comment by paramat** [comment]
> perhaps make the desert stone brick texture a little different from the other one (not only different color)

I considered grey mortar but decided to stay true to the original. However the mortar is relatively darker in the desert stone version as that looks better.
I'll merge these for now, for release.

**Comment by C1ffisme** [comment]
Awesome. :+1:

**Comment by Ekdohibs** [comment]
Looks good !

**Comment by paramat** [comment]
b24049950ed0223054dca76ab3a2c00acf2540c0

**Pull request closed without merging**
