### PR TITLE
New gravel texture.

### PR DESCRIPTION
**Pull request by sofar**
Issue #811 - new gravel texture needed.

This texture is Gambits' PixelBOX gravel light texture. Gambit
posted that his texture pack is WTFPL:
- https://forum.minetest.net/viewtopic.php?f=4&t=4990&start=50#p141196

I've made only minor modifications to this texture:
- slightly rotated and rolled some sections of pixels
- minor burn/dodge some pixels to keep high contrast
- removed lineair repeating effects

Credit goes to Gambit. Thanks.

### CODE REVIEW

**Comment by C1ffisme** [comment]
:+1:

**Comment by red-001** [comment]
:+1:

**Comment by paramat** [comment]
screenshot_20160202_012753

screenshot_20160202_013316

:+1:

**Comment by ShadowNinja** [comment]
Still has some repeating effects.  Can you fix them?  Looks much better anyways IMO.  :+1:

**Comment by sofar** [comment]
I'll do one more pass on this, There's a bit of an off-balance with one half being significantly lighter.

**Comment by paramat** [comment]
Seems okay, any texture will create repeating effects, the eye is prone to seeing them. But yes one half does seem a little lighter.

**Comment by rubenwardy** [comment]
I like it

**Comment by paramat** [comment]
The brightness bands are an illusion too, it's fine as it is.

**Comment by sofar** [comment]
Thanks for giving me some time to take another pass over this one. I've been travelling so time has been limited.

I've just pushed another version where I really carefully adjusted the balance of pebbles and matrix. I've grown some of the pebbles out to remove the lighter streaks and nudges quite a few pixels to get a more uniform spread of matrix and pebbles. The results is a lot better, which doesn't really show in the texture itself unless you load it in the game.

![]
(http://i.imgur.com/H6Xd4Hy.png)

Yes, there will always be a little tiling, but it seems every pass I do I can improve on it without destroying the local contrast and detail. Anyway, I hope people like this

**Comment by C1ffisme** [comment]
IMHO, I would make it a tad darker, to fit with a stony background. But that is my HO.

**Comment by paramat** [comment]
Will try in-game.

**Comment by sofar** [comment]
@C1ffisme I believe my screenshot was with filmic tonemapping enabled in the client, which makes it appear lighter than it is.

**Comment by paramat** [comment]
Yeah it looks better in-game ..

screenshot_20160209_044449

screenshot_20160209_044618

There's very little tiling-repetition don't worry.

**Comment by paramat** [comment]
Sorry i don't like this, the large stones are now too large and too dark so look too different from the finer gravel. It looks more like cobblestone. Also the darkness of the large stones takes away from their shadow effects. I really like your previous texture and it doesn't have any problematic repeating effects.

**Comment by paramat** [comment]
Or if you want to address the way the previous texture has vertical lines of slightly darker pebbles, just make them slightly brighter, without changing anything else.

**Comment by sofar** [comment]
@paramat hmm, well I feel that the last iteration had a bad seam, something I've spent more time on in the last pass, but I did make some of the pebbles larger in the process. I'll try to come up with something in between the previous revision and the current, i.e. fix the seam but not grow the pebbles out.

**Comment by paramat** [comment]
I think the pebbles look better when 2x2 or 2x3, at 3x3 they're too big for me. The original texture looked more consistent due to it's smaller brighter pebbles (not saying i want the original).

**Comment by sofar** [comment]
![]
(http://i.imgur.com/27RphTL.png)

Revised.

- pebbles are made smaller. Mostly 2x2 and 2x3 now.
- two small pebbles removed, moving others around to make the matrix 2px wide in more spots
- due to the matrix being lighter, I made the whole image 10% darker to prevent this from slowly becoming a lighter texture.

I think I maintained the feel of the texture. The edge smear is gone and so is the darker side, still. Tiling still is under control. Please look in-game and comment.

**Comment by sfan5** [comment]
:+1:

**Comment by C1ffisme** [comment]
It looks pretty good... I still wonder why the rocks underneath the top gravel are lighter than the top gravel itself, though.

**Comment by Thomas--S** [comment]
:+1:

**Comment by paramat** [comment]
The texture structure is good but the large stones are still a little too dark and have lost their 3D shading. If you look at Gambit's original and your original PR submission the large stones are only slightly darker than the fine material and they have L-shaped shading all aligned consistently to suggest light coming from top left or top right.

**Comment by kilbith** [comment]
I agree with paramat.

**Comment by sofar** [comment]
So, more like this: ?

![]
(http://i.imgur.com/3byRE3s.png)

**Comment by paramat** [comment]
Nice, will test in-game.

**Comment by sofar** [comment]
@paramat  hadn't pushed it until just now.

**Comment by paramat** [comment]
Okay just grabbed it. You should credit yourself for this texture since it's evolved so much, if you want you can add 'derived from a texture by Gambit WTFPL'.

**Comment by sofar** [comment]
@paramat changed the attribution around, and slightly reworded the commit message to reflect the slew of changes as well.

**Comment by paramat** [comment]
Looks good :+1:

**Comment by sofar** [comment]
Do @ShadowNinja or @sfan5 want to re-affirm the latest PR is still approved? Otherwise I think this can be merged.

**Comment by sfan5** [comment]
still good :+1:

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
5569950b26507704f603fc2e43b3cae26825c511

**Pull request closed without merging**
